window.blogPosts = [
  {
    id: "post-2",
    title: "Beach Volleyball in Destin",
    date: new Date('2024-01-15T00:00:00Z'),
    timelineHighlight: "Beach Volleyball in Destin",
    tags: ["beach volleyball", "beach"],
    snippet: "Kicked off my journey with sun, sand, and epic volleyball matches in Destin’s emerald waters.",
    image: "attachment://placeholder-destin.jpg",
    imageAlt: "Destin Beach Volleyball",
    caption: "Spiking on the white sands of Destin!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Destin on Google Maps",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 8 // 8 days in Destin
  },
  {
    id: "post-3",
    title: "Jazz and Beignets in New Orleans",
    date: new Date('2024-02-10T00:00:00Z'),
    timelineHighlight: "Jazz in New Orleans",
    tags: ["live music", "food"],
    snippet: "Soaked in the vibrant jazz scene and savored beignets in the heart of the French Quarter.",
    image: "attachment://placeholder-new-orleans.jpg",
    imageAlt: "New Orleans French Quarter",
    caption: "Jazz on the streets of New Orleans!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find New Orleans on Google Maps",
    fullLink: "#",
    location: { lat: 29.9511, lng: -90.0715, name: "New Orleans, Louisiana" },
    stayDuration: 2 // 2 days in New Orleans
  },
  {
    id: "post-4",
    title: "Rocky Mountain High in Denver",
    date: new Date('2024-04-05T00:00:00Z'),
    timelineHighlight: "Exploring Denver",
    tags: ["hiking", "city"],
    snippet: "Explored Denver’s urban charm and took in stunning views from nearby trails.",
    image: "attachment://placeholder-denver.jpg",
    imageAlt: "Denver Skyline",
    caption: "Denver’s skyline with the Rockies in the background!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Denver on Google Maps",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 1 // 1 day in Denver
  },
  {
    id: "post-5",
    title: "Skiing in Breckenridge",
    date: new Date('2024-05-01T00:00:00Z'),
    timelineHighlight: "Skiing in Breckenridge",
    tags: ["skiing", "mountains"],
    snippet: "Hit the snowy slopes of Breckenridge for an epic skiing adventure.",
    image: "attachment://placeholder-breckenridge.jpg",
    imageAlt: "Breckenridge Slopes",
    caption: "Shredding the slopes in Breckenridge!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Breckenridge on Google Maps",
    fullLink: "#",
    location: { lat: 39.4817, lng: -106.0384, name: "Breckenridge, Colorado" },
    stayDuration: 1 // 1 day in Breckenridge
  },
  {
    id: "post-6",
    title: "Snowy Adventures in Salt Lake City",
    date: new Date('2024-06-10T00:00:00Z'),
    timelineHighlight: "Snow in Salt Lake City",
    tags: ["skiing", "nature"],
    snippet: "Explored the snowy landscapes around Salt Lake City, from ski resorts to serene hikes.",
    image: "attachment://placeholder-salt-lake.jpg",
    imageAlt: "Salt Lake City Mountains",
    caption: "Winter beauty in Salt Lake City!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Salt Lake City on Google Maps",
    fullLink: "#",
    location: { lat: 40.7608, lng: -111.8910, name: "Salt Lake City, Utah" },
    stayDuration: 1 // 1 day in Salt Lake City
  },
  {
    id: "post-7",
    title: "Lights and Action in Las Vegas",
    date: new Date('2024-07-15T00:00:00Z'),
    timelineHighlight: "Lights in Las Vegas",
    tags: ["nightlife", "city"],
    snippet: "Experienced the dazzling lights and vibrant nightlife of the Las Vegas Strip.",
    image: "attachment://placeholder-las-vegas.jpg",
    imageAlt: "Las Vegas Strip",
    caption: "Bright lights of the Las Vegas Strip!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Las Vegas on Google Maps",
    fullLink: "#",
    location: { lat: 36.1699, lng: -115.1398, name: "Las Vegas, Nevada" },
    stayDuration: 1 // 1 day in Las Vegas
  },
  {
    id: "post-8",
    title: "Surf and Sun in San Diego",
    date: new Date('2024-08-20T00:00:00Z'),
    timelineHighlight: "Surfing in San Diego",
    tags: ["beach", "surfing"],
    snippet: "Caught some waves and soaked up the sun on San Diego’s beautiful beaches.",
    image: "attachment://placeholder-san-diego.jpg",
    imageAlt: "San Diego Beach",
    caption: "Surfing the waves in San Diego!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find San Diego on Google Maps",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 1 // 1 day in San Diego
  },
  {
    id: "post-9",
    title: "Island Life in Hawaii",
    date: new Date('2024-09-10T00:00:00Z'),
    timelineHighlight: "Island Life in Hawaii",
    tags: ["beach", "nature"],
    snippet: "Embraced island life in Honolulu with stunning beaches and lush hikes.",
    image: "attachment://placeholder-hawaii.jpg",
    imageAlt: "Hawaii Beach",
    caption: "Paradise found in Honolulu, Hawaii!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Honolulu on Google Maps",
    fullLink: "#",
    location: { lat: 21.3069, lng: -157.8583, name: "Honolulu, Hawaii" },
    stayDuration: 1 // 1 day in Honolulu
  },
  {
    id: "post-10",
    title: "Tropical Vibes in the Philippines",
    date: new Date('2024-10-05T00:00:00Z'),
    timelineHighlight: "Tropical Vibes in the Philippines",
    tags: ["beach", "culture"],
    snippet: "Explored the vibrant culture and pristine beaches of Manila and beyond.",
    image: "attachment://placeholder-philippines.jpg",
    imageAlt: "Philippines Beach",
    caption: "Tropical paradise in the Philippines!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Manila on Google Maps",
    fullLink: "#",
    location: { lat: 14.5995, lng: 120.9842, name: "Manila, Philippines" },
    stayDuration: 1 // 1 day in Manila
  },
  {
    id: "post-11",
    title: "Temples and Markets in Thailand",
    date: new Date('2024-11-01T00:00:00Z'),
    timelineHighlight: "Temples in Thailand",
    tags: ["culture", "markets"],
    snippet: "Immersed myself in Bangkok’s stunning temples and bustling markets.",
    image: "attachment://placeholder-thailand.jpg",
    imageAlt: "Bangkok Temple",
    caption: "Exploring the temples of Bangkok!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Bangkok on Google Maps",
    fullLink: "#",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1 // 1 day in Bangkok
  },
  {
    id: "post-12",
    title: "Tech and Tradition in Japan",
    date: new Date('2024-12-10T00:00:00Z'),
    timelineHighlight: "Tech in Japan",
    tags: ["culture", "city"],
    snippet: "Experienced the blend of tech and tradition in Tokyo’s vibrant streets.",
    image: "attachment://placeholder-japan.jpg",
    imageAlt: "Tokyo Skyline",
    caption: "Tokyo’s neon lights and traditions!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Tokyo on Google Maps",
    fullLink: "#",
    location: { lat: 35.6762, lng: 139.6503, name: "Tokyo, Japan" },
    stayDuration: 1 // 1 day in Tokyo
  },
  {
    id: "post-13",
    title: "Beaches and Beats in Miami",
    date: new Date('2025-01-15T00:00:00Z'),
    timelineHighlight: "Beaches in Miami",
    tags: ["beach", "nightlife"],
    snippet: "Danced to the beats and relaxed on the beaches of Miami.",
    image: "attachment://placeholder-miami.jpg",
    imageAlt: "Miami Beach",
    caption: "Sunset vibes on Miami Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami on Google Maps",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1 // 1 day in Miami
  },
  {
    id: "post-1",
    title: "An Epic Day Vibing in Austin",
    date: new Date('2025-05-10T00:00:00Z'),
    timelineHighlight: "Volleyball & Coffee in Austin",
    tags: ["beach volleyball", "coffee", "hookah"],
    snippet: "Austin, Texas, knows how to deliver a day packed with energy, and today was a testament to that. From a double espresso with a jaw-dropping skyline view to spiking volleyballs and chilling at Mezze, here’s how I soaked up ATX’s best.",
    image: "attachment://cosmic-skyline.jpg",
    imageAlt: "Austin Skyline from Cosmic Coffee",
    caption: "The breathtaking view of downtown Austin from Cosmic Coffee, complete with a red train cruising by and modern buildings under a perfect sky.",
    mapLink: "https://maps.app.goo.gl/5gKqL9nL8J3mX5zK7",
    mapText: "📍 Find Cosmic Coffee on Google Maps",
    fullLink: "austin-post.html",
    location: { lat: 30.2672, lng: -97.7431, name: "Austin, Texas" },
    stayDuration: 10 // 10 days in Austin
  }
].sort((a, b) => a.date - b.date); // Sort posts by date ascending