window.momentsInTime = [
  {
    id: "medellin-2022-07-02",
    title: "Exploring Medellín’s Markets",
    date: new Date('2022-07-02T00:00:00Z'),
    timelineHighlight: "Medellín Markets",
    tags: ["culture", "city"],
    snippet: "Wandered through Medellín’s bustling markets, soaking in the local vibes at Homecenter and beyond.",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 30
  },
  {
    id: "medellin-2022-11-01",
    title: "Vibrant Streets of Medellín",
    date: new Date('2022-11-01T00:00:00Z'),
    timelineHighlight: "Medellín Culture",
    tags: ["culture", "city"],
    snippet: "Dived into the colorful streets of Medellín, from Comuna 13's street art to lively salsa nights.",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 60
  },
  {
    id: "st-petersburg-2023-01-01",
    title: "Sun and Art in St. Petersburg",
    date: new Date('2023-01-01T00:00:00Z'),
    timelineHighlight: "St. Petersburg Art",
    tags: ["beach", "art"],
    snippet: "Soaked up the sun and explored vibrant murals in St. Petersburg’s artsy downtown.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 217
  },
  {
    id: "miami-2023-08-07",
    title: "Beaches and Beats in Miami",
    date: new Date('2023-08-07T00:00:00Z'),
    timelineHighlight: "Miami Nightlife",
    tags: ["beach", "nightlife"],
    snippet: "Danced to the beats and relaxed on the vibrant beaches of South Beach, Miami.",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1
  },
  {
    id: "beirut-2023-08-09",
    title: "History and Vibes in Beirut",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Beirut Culture",
    tags: ["culture", "history"],
    snippet: "Explored Beirut’s historic souks and vibrant nightlife along the Mediterranean coast.",
    fullLink: "#",
    location: { lat: 33.8938, lng: 35.5018, name: "Beirut, Lebanon" },
    stayDuration: 8
  },
  {
    id: "baalbek-2023-08-09",
    title: "Ancient Ruins in Baalbek",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Baalbek Ruins",
    tags: ["history", "culture"],
    snippet: "Explored the majestic Temple of Bacchus in Baalbek, a stunning journey into Lebanon’s ancient past.",
    fullLink: "#",
    location: { lat: 34.0069, lng: 36.2039, name: "Baalbek, Lebanon" },
    stayDuration: 1
  },
  {
    id: "athens-2023-08-18",
    title: "Ancient Wonders in Athens",
    date: new Date('2023-08-18T00:00:00Z'),
    timelineHighlight: "Athens History",
    tags: ["history", "culture"],
    snippet: "Walked through history at the Acropolis and savored Greek flavors in Plaka.",
    fullLink: "#",
    location: { lat: 37.9838, lng: 23.7275, name: "Athens, Greece" },
    stayDuration: 3
  },
  {
    id: "barcelona-2023-08-21",
    title: "Art and Architecture in Barcelona",
    date: new Date('2023-08-21T00:00:00Z'),
    timelineHighlight: "Barcelona Art",
    tags: ["art", "architecture"],
    snippet: "Marveled at Gaudí’s masterpieces and strolled along La Rambla in vibrant Barcelona.",
    fullLink: "#",
    location: { lat: 41.3851, lng: 2.1734, name: "Barcelona, Spain" },
    stayDuration: 23
  },
  {
    id: "sofia-2023-09-13",
    title: "Hidden Gems in Sofia",
    date: new Date('2023-09-13T00:00:00Z'),
    timelineHighlight: "Sofia Culture",
    tags: ["culture", "history"],
    snippet: "Discovered Sofia’s historic churches and vibrant markets in Bulgaria’s capital.",
    fullLink: "#",
    location: { lat: 42.6977, lng: 23.3219, name: "Sofia, Bulgaria" },
    stayDuration: 38
  },
  {
    id: "dubai-2023-10-05",
    title: "Luxury and Adventure in Dubai",
    date: new Date('2023-10-05T00:00:00Z'),
    timelineHighlight: "Dubai Skyline",
    tags: ["city", "luxury"],
    snippet: "Admired Dubai’s towering skyline and explored the desert dunes on an epic adventure.",
    fullLink: "#",
    location: { lat: 25.2048, lng: 55.2708, name: "Dubai, United Arab Emirates" },
    stayDuration: 4
  },
  {
    id: "varna-2023-10-18",
    title: "Black Sea Bliss in Varna",
    date: new Date('2023-10-18T00:00:00Z'),
    timelineHighlight: "Varna Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Varna’s Black Sea beaches and explored its ancient Roman baths.",
    fullLink: "#",
    location: { lat: 43.2141, lng: 27.9147, name: "Varna, Bulgaria" },
    stayDuration: 39
  },
  {
    id: "chattanooga-2024-05-14",
    title: "Outdoor Vibes in Chattanooga",
    date: new Date('2024-05-14T00:00:00Z'),
    timelineHighlight: "Chattanooga Trails",
    tags: ["hiking", "nature"],
    snippet: "Hiked scenic trails and explored the vibrant riverfront in Chattanooga.",
    fullLink: "#",
    location: { lat: 35.0456, lng: -85.3097, name: "Chattanooga, Tennessee" },
    stayDuration: 5
  },
  {
    id: "st-petersburg-2024-05-19",
    title: "Back to St. Petersburg’s Shores",
    date: new Date('2024-05-19T00:00:00Z'),
    timelineHighlight: "St. Petersburg Beaches",
    tags: ["beach", "art"],
    snippet: "Returned to St. Petersburg for more beach vibes and local art galleries.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 12
  },
  {
    id: "chicago-2024-06-01",
    title: "Windy City Adventures in Chicago",
    date: new Date('2024-06-01T00:00:00Z'),
    timelineHighlight: "Chicago Skyline",
    tags: ["city", "culture"],
    snippet: "Explored Chicago’s iconic skyline, deep-dish pizza, and vibrant art scene.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 60
  },
  {
    id: "clearwater-2024-08-01",
    title: "Sunsets in Clearwater",
    date: new Date('2024-08-01T00:00:00Z'),
    timelineHighlight: "Clearwater Beaches",
    tags: ["beach", "nature"],
    snippet: "Chased epic sunsets and relaxed on the white sands of Clearwater Beach.",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 6
  },
  {
    id: "miami-beach-2024-08-08",
    title: "Vibrant Miami Beach",
    date: new Date('2024-08-08T00:00:00Z'),
    timelineHighlight: "Miami Beach Vibes",
    tags: ["beach", "nightlife"],
    snippet: "Soaked up the sun and danced through the night in Miami Beach’s lively scene.",
    fullLink: "#",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7
  },
  {
    id: "hermosa-beach-2024-08-15",
    title: "Chill Vibes in Hermosa Beach",
    date: new Date('2024-08-15T00:00:00Z'),
    timelineHighlight: "Hermosa Beach Surf",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and enjoyed laid-back vibes on Hermosa Beach’s sunny shores.",
    fullLink: "#",
    location: { lat: 33.8622, lng: -118.3995, name: "Hermosa Beach, California" },
    stayDuration: 7
  },
  {
    id: "san-diego-2024-08-22",
    title: "Surf and Sun in San Diego",
    date: new Date('2024-08-22T00:00:00Z'),
    timelineHighlight: "San Diego Surfing",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and soaked up the sun on San Diego’s beautiful beaches.",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 9
  },
  {
    id: "honolulu-2024-09-01",
    title: "Island Life in Honolulu",
    date: new Date('2024-09-01T00:00:00Z'),
    timelineHighlight: "Honolulu Beaches",
    tags: ["beach", "nature"],
    snippet: "Embraced island life in Honolulu with stunning beaches and lush hikes.",
    fullLink: "#",
    location: { lat: 21.3069, lng: -157.8583, name: "Honolulu, Hawaii" },
    stayDuration: 38
  },
  {
    id: "st-petersburg-2024-10-10",
    title: "St. Petersburg’s Coastal Charm",
    date: new Date('2024-10-10T00:00:00Z'),
    timelineHighlight: "St. Petersburg Sunsets",
    tags: ["beach", "art"],
    snippet: "Back again to St. Petersburg for coastal sunsets and local art vibes.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 6
  },
  {
    id: "destin-2024-10-16",
    title: "Beach Volleyball in Destin",
    date: new Date('2024-10-16T00:00:00Z'),
    timelineHighlight: "Destin Volleyball",
    tags: ["beach volleyball", "beach"],
    snippet: "Kicked off with sun, sand, and epic volleyball matches in Destin’s emerald waters.",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 5
  },
  {
    id: "miami-2024-10-23",
    title: "Miami’s Electric Energy",
    date: new Date('2024-10-23T00:00:00Z'),
    timelineHighlight: "Miami Beaches",
    tags: ["beach", "nightlife"],
    snippet: "Returned to Miami for more beach days and electric nightlife in South Beach.",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 8
  },
  {
    id: "playa-del-carmen-2024-11-01",
    title: "Mayan Riviera Magic in Playa del Carmen",
    date: new Date('2024-11-01T00:00:00Z'),
    timelineHighlight: "Playa del Carmen Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Playa del Carmen’s beaches and explored nearby Mayan ruins.",
    fullLink: "#",
    location: { lat: 20.6296, lng: -87.0739, name: "Playa del Carmen, Mexico" },
    stayDuration: 14
  },
  {
    id: "clearwater-2024-11-16",
    title: "More Clearwater Sunsets",
    date: new Date('2024-11-16T00:00:00Z'),
    timelineHighlight: "Clearwater Sunsets",
    tags: ["beach", "nature"],
    snippet: "Back to Clearwater for more stunning sunsets and beach relaxation.",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 12
  },
  {
    id: "denver-2024-11-20",
    title: "Denver’s Urban Pulse",
    date: new Date('2024-11-20T00:00:00Z'),
    timelineHighlight: "Denver City",
    tags: ["city", "culture"],
    snippet: "Dove into Denver’s vibrant urban scene, exploring Broadway and the city’s eclectic neighborhoods.",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3
  },
  {
    id: "denver-2024-11-28",
    title: "Rocky Mountain High in Denver",
    date: new Date('2024-11-28T00:00:00Z'),
    timelineHighlight: "Denver Trails",
    tags: ["hiking", "city"],
    snippet: "Explored Denver’s urban charm and took in stunning views from nearby trails.",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3
  },
  {
    id: "breckenridge-2024-12-01",
    title: "Skiing in Breckenridge",
    date: new Date('2024-12-01T00:00:00Z'),
    timelineHighlight: "Breckenridge Slopes",
    tags: ["skiing", "mountains"],
    snippet: "Hit the snowy slopes of Breckenridge for an epic skiing adventure.",
    fullLink: "#",
    location: { lat: 39.4817, lng: -106.0384, name: "Breckenridge, Colorado" },
    stayDuration: 30
  },
  {
    id: "miami-beach-2024-12-30",
    title: "Miami Beach Winter Escape",
    date: new Date('2024-12-30T00:00:00Z'),
    timelineHighlight: "Miami Beach Winter",
    tags: ["beach", "nightlife"],
    snippet: "Escaped winter with sunny days and vibrant nights in Miami Beach.",
    fullLink: "miami-beach-2024-12-30.html",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 34
  },
  {
    id: "st-petersburg-2025-02-02",
    title: "St. Petersburg’s Winter Glow",
    date: new Date('2025-02-02T00:00:00Z'),
    timelineHighlight: "St. Petersburg Winter",
    tags: ["beach", "art"],
    snippet: "Enjoyed winter warmth and art-filled streets in St. Petersburg.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 5
  },
  {
    id: "sao-paulo-2025-02-07",
    title: "Urban Energy in São Paulo",
    date: new Date('2025-02-07T00:00:00Z'),
    timelineHighlight: "São Paulo Culture",
    tags: ["city", "culture"],
    snippet: "Immersed in São Paulo’s bustling streets, street art, and vibrant food scene.",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 9
  },
  {
    id: "rio-de-janeiro-2025-02-16",
    title: "Carnival Vibes in Rio de Janeiro",
    date: new Date('2025-02-16T00:00:00Z'),
    timelineHighlight: "Rio Beaches",
    tags: ["beach", "culture"],
    snippet: "Danced to samba rhythms and relaxed on Copacabana Beach in Rio.",
    fullLink: "#",
    location: { lat: -22.9068, lng: -43.1729, name: "Rio de Janeiro, Brazil" },
    stayDuration: 11
  },
  {
    id: "sao-paulo-2025-02-27",
    title: "Back to São Paulo’s Beat",
    date: new Date('2025-02-27T00:00:00Z'),
    timelineHighlight: "São Paulo Art",
    tags: ["city", "art"],
    snippet: "Returned to São Paulo for more street art and vibrant nightlife.",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 10
  },
  {
    id: "st-petersburg-2025-03-09",
    title: "Spring in St. Petersburg",
    date: new Date('2025-03-09T00:00:00Z'),
    timelineHighlight: "St. Petersburg Spring",
    tags: ["beach", "art"],
    snippet: "Welcomed spring with beach days and art walks in St. Petersburg.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 44
  },
  {
    id: "williston-2025-03-13",
    title: "Diving Devil’s Den in Williston",
    date: new Date('2025-03-13T00:00:00Z'),
    timelineHighlight: "Devil’s Den Spring",
    tags: ["nature", "adventure"],
    snippet: "Dove into the crystal-clear waters of Devil’s Den Prehistoric Spring for an unforgettable adventure.",
    fullLink: "#",
    location: { lat: 29.4086, lng: -82.4757, name: "Williston, Florida" },
    stayDuration: 1
  },
  {
    id: "chicago-2025-03-29",
    title: "Spring Vibes in Chicago",
    date: new Date('2025-03-29T00:00:00Z'),
    timelineHighlight: "Chicago Spring",
    tags: ["city", "culture"],
    snippet: "Embraced Chicago’s spring energy, visiting Paylocity and exploring the city’s vibrant neighborhoods.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 5
  },
  {
    id: "destin-2025-04-22",
    title: "More Destin Beach Days",
    date: new Date('2025-04-22T00:00:00Z'),
    timelineHighlight: "Destin Beaches",
    tags: ["beach volleyball", "beach"],
    snippet: "Back to Destin for more volleyball and emerald-green beach days.",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 6
  },
  {
    id: "new-orleans-2025-04-28",
    title: "Jazz and Beignets in New Orleans",
    date: new Date('2025-04-28T00:00:00Z'),
    timelineHighlight: "New Orleans Jazz",
    tags: ["live music", "food"],
    snippet: "Soaked in the vibrant jazz scene and savored beignets in the French Quarter.",
    fullLink: "#",
    location: { lat: 29.9511, lng: -90.0715, name: "New Orleans, Louisiana" },
    stayDuration: 3
  },
  {
    id: "houston-2025-05-01",
    title: "Urban Exploration in Houston",
    date: new Date('2025-05-01T00:00:00Z'),
    timelineHighlight: "Houston Culture",
    tags: ["city", "culture"],
    snippet: "Explored Houston’s museums and vibrant food scene in a quick city stop.",
    fullLink: "#",
    location: { lat: 29.7604, lng: -95.3698, name: "Houston, Texas" },
    stayDuration: 1
  },
  {
    id: "austin-2025-05-02",
    title: "An Epic Day Vibing in Austin",
    date: new Date('2025-05-02T00:00:00Z'),
    timelineHighlight: "Austin Volleyball",
    tags: ["beach volleyball", "coffee"],
    snippet: "From a double espresso with a jaw-dropping skyline view to spiking volleyballs, Austin delivered energy and vibes.",
    fullLink: "#",
    location: { lat: 30.2672, lng: -97.7431, name: "Austin, Texas" },
    stayDuration: 10
  },
  {
    id: "boulder-2025-05-13",
    title: "Chasing Vibes in Boulder",
    date: new Date('2025-05-13T00:00:00Z'),
    timelineHighlight: "Coffee & Music in Boulder",
    tags: ["coffee", "live music", "wellness"],
    snippet: "Soaking up Boulder’s chill vibes with live music at Trident, unique tonics at Tonic Alchemy Lounge, and daily recovery at the Rec Center.",
    fullLink: "boulder-2025-05-17.html",
    location: { lat: 40.0150, lng: -105.2705, name: "Boulder, Colorado" },
    stayDuration: 7
  },
  {
    id: "san-diego-2025-05-20",
    title: "San Diego Whirlwind: Yoga, Thai, and Line Dancing",
    date: new Date('2025-05-20T00:00:00Z'),
    timelineHighlight: "San Diego Line Dancing",
    tags: ["yoga", "friends", "line dancing", "food"],
    snippet: "Landed in San Diego, picked up by Wouter for hot yoga at Indie Yoga, regional pad Thai at Pad Thai Stand, and country line dancing at Moonshine Beach with Wouter and Ray dancing rebelliously in the middle—Ray’s punctuality ensured a smooth airport send-off.",
    fullLink: "san-diego-2025-05-20.html",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 1
  },
  {
    id: "fort-lauderdale-2025-05-21",
    title: "Volleyball and Vibes in Fort Lauderdale",
    date: new Date('2025-05-21T00:00:00Z'),
    timelineHighlight: "Fort Lauderdale Volleyball",
    tags: ["beach", "beach volleyball", "friends"],
    snippet: "Arrived in Fort Lauderdale after a Denver layover, staying with Bartek for work, beach volleyball in Deerfield, and a relaxing massage together.",
    fullLink: "fort-lauderdale-2025-05-21.html",
    location: { lat: 26.1224, lng: -80.1373, name: "Fort Lauderdale, Florida" },
    stayDuration: 2
  },
  {
    id: "miami-beach-2025-05-23",
    title: "South Beach Volleyball, Bachata, and a Drive to St. Pete",
    date: new Date('2025-05-23T00:00:00Z'),
    timelineHighlight: "South Beach Adventures",
    tags: ["beach", "beach volleyball", "nightlife", "friends", "bachata"],
    snippet: "Played high-energy volleyball, danced bachata at Alain’s, and drove to St. Pete",
    fullLink: "miami-beach-2025-05-23.html",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7
  },
  {
    id: "tampa-2025-05-30",
    title: "Tampa Weekend: Road Trips, Brazilian Feasts, and St. Pete Yoga Vibes",
    date: new Date('2025-05-30T00:00:00Z'),
    timelineHighlight: "Tampa Bay Vibes",
    tags: ["travel", "yoga", "food", "friends", "relocation"],
    snippet: "Cruised from Miami to St. Pete, feasted at a Brazilian steakhouse, flowed through yoga in St. Petersburg, and recovered in Clearwater while prepping for Hawaii.",
    image: "attachment://tampa-2025-05-30-1.jpg",
    imageAlt: "Post yoga smoothie",
    caption: "Leigha, Leo & Paul enjoying a smoothie after Yoga",
    fullLink: "tampa-2025-05-30.html",
    location: { lat: 27.9506, lng: -82.4572, name: "Tampa, Florida" },
    stayDuration: 3
  },
  {
    id: "san-diego-2025-06-01",
    title: "San Diego Coastal Reset",
    date: new Date('2025-06-01T00:00:00Z'),
    timelineHighlight: "San Diego Beaches",
    tags: ["beach", "surfing"],
    snippet: "Will head back to San Diego for two weeks of surfing, beach vibes, and gearing up for the Hawaii move.",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 14
  },
  {
    id: "oahu-2025-06-15",
    title: "New Beginnings in Oahu",
    date: new Date('2025-06-15T00:00:00Z'),
    timelineHighlight: "Oahu New Home",
    tags: ["beach", "nature", "relocation"],
    snippet: "Will launch a new chapter in Oahu, settling into island life with beaches and volcanic trails.",
    fullLink: "#",
    location: { lat: 21.4389, lng: -158.0001, name: "Oahu, Hawaii" },
    stayDuration: 110
  },
  {
    id: "chicago-2025-10-03",
    title: "Chicago’s Fall Charm",
    date: new Date('2025-10-03T00:00:00Z'),
    timelineHighlight: "Chicago Fall",
    tags: ["city", "culture"],
    snippet: "Will revisit Chicago to enjoy fall vibes, art walks, and cozy coffee shops.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 5
  },
  {
    id: "playa-del-carmen-2025-10-24",
    title: "Beach Volleyball Tournament in Playa del Carmen",
    date: new Date('2025-10-24T00:00:00Z'),
    timelineHighlight: "Playa Volleyball",
    tags: ["beach volleyball", "beach", "friends"],
    snippet: "Will team up with Zacharias to smash serves and dive for digs at a thrilling beach volleyball tournament in Playa del Carmen.",
    fullLink: "playa-del-carmen-2025-10-28.html",
    location: { lat: 20.6296, lng: -87.0739, name: "Playa del Carmen, Mexico" },
    stayDuration: 10
  },
  {
    id: "canggu-2025-11-03",
    title: "Yoga Retreat in Canggu",
    date: new Date('2025-11-03T00:00:00Z'),
    timelineHighlight: "Canggu Yoga",
    tags: ["yoga", "beach", "wellness", "friends"],
    snippet: "Will join Leigha, Hallie, and Leo for a rejuvenating yoga retreat amid Canggu’s rice fields and beaches.",
    fullLink: "#",
    location: { lat: -8.6596, lng: 115.1326, name: "Canggu, Indonesia" },
    stayDuration: 21
  }
].sort((a, b) => a.date - b.date);