window.momentsInTime = 
[
  {
    id: "medellin-2022-07-02",
    title: "Exploring Medellín’s Markets",
    date: new Date('2022-07-02T00:00:00Z'),
    timelineHighlight: "Medellín Markets",
    tags: ["culture", "city"],
    snippet: "Wandered through Medellín’s bustling markets, soaking in the local vibes at Homecenter and beyond.",
    image: "attachment://placeholder-medellin.jpg",
    imageAlt: "Medellín Market",
    caption: "Vibrant market scenes in Medellín!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Medellín on Google Maps",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 30
  },
  {
    id: "medellin-2022-11-01",
    title: "Vibrant Streets of Medellín",
    date: new Date('2022-11-01T00:00:00Z'),
    timelineHighlight: "Medellín Culture",
    tags: ["culture", "city"],
    snippet: "Dived into the colorful streets of Medellín, from Comuna 13's street art to lively salsa nights.",
    image: "attachment://placeholder-medellin.jpg",
    imageAlt: "Medellín Street Art",
    caption: "Vibrant murals in Comuna 13, Medellín!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Medellín on Google Maps",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 60
  },
  {
    id: "st-petersburg-2023-01-01",
    title: "Sun and Art in St. Petersburg",
    date: new Date('2023-01-01T00:00:00Z'),
    timelineHighlight: "St. Petersburg Art",
    tags: ["beach", "art"],
    snippet: "Soaked up the sun and explored vibrant murals in St. Petersburg’s artsy downtown.",
    image: "attachment://placeholder-st-petersburg.jpg",
    imageAlt: "St. Petersburg Murals",
    caption: "Colorful street art in St. Petersburg!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find St. Petersburg on Google Maps",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 217
  },
  {
    id: "miami-2023-08-07",
    title: "Beaches and Beats in Miami",
    date: new Date('2023-08-07T00:00:00Z'),
    timelineHighlight: "Miami Nightlife",
    tags: ["beach", "nightlife"],
    snippet: "Danced to the beats and relaxed on the vibrant beaches of South Beach, Miami.",
    image: "attachment://placeholder-miami.jpg",
    imageAlt: "Miami Beach",
    caption: "Sunset vibes on Miami Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami on Google Maps",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1
  },
  {
    id: "beirut-2023-08-09",
    title: "History and Vibes in Beirut",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Beirut Culture",
    tags: ["culture", "history"],
    snippet: "Explored Beirut’s historic souks and vibrant nightlife along the Mediterranean coast.",
    image: "attachment://placeholder-beirut.jpg",
    imageAlt: "Beirut Souks",
    caption: "Bustling streets of Beirut!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Beirut on Google Maps",
    fullLink: "#",
    location: { lat: 33.8938, lng: 35.5018, name: "Beirut, Lebanon" },
    stayDuration: 8
  },
  {
    id: "baalbek-2023-08-09",
    title: "Ancient Ruins in Baalbek",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Baalbek Ruins",
    tags: ["history", "culture"],
    snippet: "Explored the majestic Temple of Bacchus in Baalbek, a stunning journey into Lebanon’s ancient past.",
    image: "attachment://placeholder-baalbek.jpg",
    imageAlt: "Temple of Bacchus",
    caption: "The grandeur of Baalbek’s ruins!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Baalbek on Google Maps",
    fullLink: "#",
    location: { lat: 34.0069, lng: 36.2039, name: "Baalbek, Lebanon" },
    stayDuration: 1
  },
  {
    id: "athens-2023-08-18",
    title: "Ancient Wonders in Athens",
    date: new Date('2023-08-18T00:00:00Z'),
    timelineHighlight: "Athens History",
    tags: ["history", "culture"],
    snippet: "Walked through history at the Acropolis and savored Greek flavors in Plaka.",
    image: "attachment://placeholder-athens.jpg",
    imageAlt: "Athens Acropolis",
    caption: "The Acropolis glowing at dusk!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Athens on Google Maps",
    fullLink: "#",
    location: { lat: 37.9838, lng: 23.7275, name: "Athens, Greece" },
    stayDuration: 3
  },
  {
    id: "barcelona-2023-08-21",
    title: "Art and Architecture in Barcelona",
    date: new Date('2023-08-21T00:00:00Z'),
    timelineHighlight: "Barcelona Art",
    tags: ["art", "architecture"],
    snippet: "Marveled at Gaudí’s masterpieces and strolled along La Rambla in vibrant Barcelona.",
    image: "attachment://placeholder-barcelona.jpg",
    imageAlt: "Barcelona Sagrada Familia",
    caption: "Gaudí’s Sagrada Familia in all its glory!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Barcelona on Google Maps",
    fullLink: "#",
    location: { lat: 41.3851, lng: 2.1734, name: "Barcelona, Spain" },
    stayDuration: 23
  },
  {
    id: "sofia-2023-09-13",
    title: "Hidden Gems in Sofia",
    date: new Date('2023-09-13T00:00:00Z'),
    timelineHighlight: "Sofia Culture",
    tags: ["culture", "history"],
    snippet: "Discovered Sofia’s historic churches and vibrant markets in Bulgaria’s capital.",
    image: "attachment://placeholder-sofia.jpg",
    imageAlt: "Sofia Cathedral",
    caption: "Alexander Nevsky Cathedral in Sofia!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Sofia on Google Maps",
    fullLink: "#",
    location: { lat: 42.6977, lng: 23.3219, name: "Sofia, Bulgaria" },
    stayDuration: 38
  },
  {
    id: "dubai-2023-10-05",
    title: "Luxury and Adventure in Dubai",
    date: new Date('2023-10-05T00:00:00Z'),
    timelineHighlight: "Dubai Skyline",
    tags: ["city", "luxury"],
    snippet: "Admired Dubai’s towering skyline and explored the desert dunes on an epic adventure.",
    image: "attachment://placeholder-dubai.jpg",
    imageAlt: "Dubai Skyline",
    caption: "Burj Khalifa piercing the Dubai sky!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Dubai on Google Maps",
    fullLink: "#",
    location: { lat: 25.2048, lng: 55.2708, name: "Dubai, United Arab Emirates" },
    stayDuration: 4
  },
  {
    id: "varna-2023-10-18",
    title: "Black Sea Bliss in Varna",
    date: new Date('2023-10-18T00:00:00Z'),
    timelineHighlight: "Varna Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Varna’s Black Sea beaches and explored its ancient Roman baths.",
    image: "attachment://placeholder-varna.jpg",
    imageAlt: "Varna Beach",
    caption: "Sunset on Varna’s Black Sea coast!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Varna on Google Maps",
    fullLink: "#",
    location: { lat: 43.2141, lng: 27.9147, name: "Varna, Bulgaria" },
    stayDuration: 39
  },
  {
    id: "chattanooga-2024-05-14",
    title: "Outdoor Vibes in Chattanooga",
    date: new Date('2024-05-14T00:00:00Z'),
    timelineHighlight: "Chattanooga Trails",
    tags: ["hiking", "nature"],
    snippet: "Hiked scenic trails and explored the vibrant riverfront in Chattanooga.",
    image: "attachment://placeholder-chattanooga.jpg",
    imageAlt: "Chattanooga Riverfront",
    caption: "Chattanooga’s riverfront at golden hour!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Chattanooga on Google Maps",
    fullLink: "#",
    location: { lat: 35.0456, lng: -85.3097, name: "Chattanooga, Tennessee" },
    stayDuration: 5
  },
  {
    id: "st-petersburg-2024-05-19",
    title: "Back to St. Petersburg’s Shores",
    date: new Date('2024-05-19T00:00:00Z'),
    timelineHighlight: "St. Petersburg Beaches",
    tags: ["beach", "art"],
    snippet: "Returned to St. Petersburg for more beach vibes and local art galleries.",
    image: "attachment://placeholder-st-petersburg.jpg",
    imageAlt: "St. Petersburg Beach",
    caption: "Chasing sunsets in St. Petersburg!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find St. Petersburg on Google Maps",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 12
  },
  {
    id: "chicago-2024-06-01",
    title: "Windy City Adventures in Chicago",
    date: new Date('2024-06-01T00:00:00Z'),
    timelineHighlight: "Chicago Skyline",
    tags: ["city", "culture"],
    snippet: "Explored Chicago’s iconic skyline, deep-dish pizza, and vibrant art scene.",
    image: "attachment://placeholder-chicago.jpg",
    imageAlt: "Chicago Skyline",
    caption: "Chicago’s skyline from the Adler Planetarium!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Chicago on Google Maps",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 60
  },
  {
    id: "clearwater-2024-08-01",
    title: "Sunsets in Clearwater",
    date: new Date('2024-08-01T00:00:00Z'),
    timelineHighlight: "Clearwater Beaches",
    tags: ["beach", "nature"],
    snippet: "Chased epic sunsets and relaxed on the white sands of Clearwater Beach.",
    image: "attachment://placeholder-clearwater.jpg",
    imageAlt: "Clearwater Beach",
    caption: "Golden hour on Clearwater Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Clearwater on Google Maps",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 6
  },
  {
    id: "miami-beach-2024-08-08",
    title: "Vibrant Miami Beach",
    date: new Date('2024-08-08T00:00:00Z'),
    timelineHighlight: "Miami Beach Vibes",
    tags: ["beach", "nightlife"],
    snippet: "Soaked up the sun and danced through the night in Miami Beach’s lively scene.",
    image: "attachment://placeholder-miami-beach.jpg",
    imageAlt: "Miami Beach",
    caption: "Neon nights in Miami Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami Beach on Google Maps",
    fullLink: "#",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7
  },
  {
    id: "hermosa-beach-2024-08-15",
    title: "Chill Vibes in Hermosa Beach",
    date: new Date('2024-08-15T00:00:00Z'),
    timelineHighlight: "Hermosa Beach Surf",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and enjoyed laid-back vibes on Hermosa Beach’s sunny shores.",
    image: "attachment://placeholder-hermosa-beach.jpg",
    imageAlt: "Hermosa Beach",
    caption: "Surf’s up in Hermosa Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Hermosa Beach on Google Maps",
    fullLink: "#",
    location: { lat: 33.8622, lng: -118.3995, name: "Hermosa Beach, California" },
    stayDuration: 7
  },
  {
    id: "san-diego-2024-08-22",
    title: "Surf and Sun in San Diego",
    date: new Date('2024-08-22T00:00:00Z'),
    timelineHighlight: "San Diego Surfing",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and soaked up the sun on San Diego’s beautiful beaches.",
    image: "attachment://placeholder-san-diego.jpg",
    imageAlt: "San Diego Beach",
    caption: "Surfing the waves in San Diego!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find San Diego on Google Maps",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 9
  },
  {
    id: "honolulu-2024-09-01",
    title: "Island Life in Honolulu",
    date: new Date('2024-09-01T00:00:00Z'),
    timelineHighlight: "Honolulu Beaches",
    tags: ["beach", "nature"],
    snippet: "Embraced island life in Honolulu with stunning beaches and lush hikes.",
    image: "attachment://placeholder-hawaii.jpg",
    imageAlt: "Honolulu Beach",
    caption: "Paradise found in Honolulu, Hawaii!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Honolulu on Google Maps",
    fullLink: "#",
    location: { lat: 21.3069, lng: -157.8583, name: "Honolulu, Hawaii" },
    stayDuration: 38
  },
  {
    id: "st-petersburg-2024-10-10",
    title: "St. Petersburg’s Coastal Charm",
    date: new Date('2024-10-10T00:00:00Z'),
    timelineHighlight: "St. Petersburg Sunsets",
    tags: ["beach", "art"],
    snippet: "Back again to St. Petersburg for coastal sunsets and local art vibes.",
    image: "attachment://placeholder-st-petersburg.jpg",
    imageAlt: "St. Petersburg Sunset",
    caption: "St. Petersburg’s golden hour glow!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find St. Petersburg on Google Maps",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 6
  },
  {
    id: "destin-2024-10-16",
    title: "Beach Volleyball in Destin",
    date: new Date('2024-10-16T00:00:00Z'),
    timelineHighlight: "Destin Volleyball",
    tags: ["beach volleyball", "beach"],
    snippet: "Kicked off with sun, sand, and epic volleyball matches in Destin’s emerald waters.",
    image: "attachment://placeholder-destin.jpg",
    imageAlt: "Destin Beach Volleyball",
    caption: "Spiking on the white sands of Destin!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Destin on Google Maps",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 5
  },
  {
    id: "miami-2024-10-23",
    title: "Miami’s Electric Energy",
    date: new Date('2024-10-23T00:00:00Z'),
    timelineHighlight: "Miami Beaches",
    tags: ["beach", "nightlife"],
    snippet: "Returned to Miami for more beach days and electric nightlife in South Beach.",
    image: "attachment://placeholder-miami.jpg",
    imageAlt: "Miami Beach",
    caption: "Miami’s vibrant South Beach scene!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami on Google Maps",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 8
  },
  {
    id: "playa-del-carmen-2024-11-01",
    title: "Mayan Riviera Magic in Playa del Carmen",
    date: new Date('2024-11-01T00:00:00Z'),
    timelineHighlight: "Playa del Carmen Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Playa del Carmen’s beaches and explored nearby Mayan ruins.",
    image: "attachment://placeholder-playa-del-carmen.jpg",
    imageAlt: "Playa del Carmen Beach",
    caption: "Turquoise waters in Playa del Carmen!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Playa del Carmen on Google Maps",
    fullLink: "#",
    location: { lat: 20.6296, lng: -87.0739, name: "Playa del Carmen, Mexico" },
    stayDuration: 14
  },
  {
    id: "clearwater-2024-11-16",
    title: "More Clearwater Sunsets",
    date: new Date('2024-11-16T00:00:00Z'),
    timelineHighlight: "Clearwater Sunsets",
    tags: ["beach", "nature"],
    snippet: "Back to Clearwater for more stunning sunsets and beach relaxation.",
    image: "attachment://placeholder-clearwater.jpg",
    imageAlt: "Clearwater Sunset",
    caption: "Clearwater’s sunset magic!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Clearwater on Google Maps",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 12
  },
  {
    id: "denver-2024-11-20",
    title: "Denver’s Urban Pulse",
    date: new Date('2024-11-20T00:00:00Z'),
    timelineHighlight: "Denver City",
    tags: ["city", "culture"],
    snippet: "Dove into Denver’s vibrant urban scene, exploring Broadway and the city’s eclectic neighborhoods.",
    image: "attachment://placeholder-denver.jpg",
    imageAlt: "Denver Streets",
    caption: "Denver’s lively urban vibe!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Denver on Google Maps",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3
  },
  {
    id: "denver-2024-11-28",
    title: "Rocky Mountain High in Denver",
    date: new Date('2024-11-28T00:00:00Z'),
    timelineHighlight: "Denver Trails",
    tags: ["hiking", "city"],
    snippet: "Explored Denver’s urban charm and took in stunning views from nearby trails.",
    image: "attachment://placeholder-denver.jpg",
    imageAlt: "Denver Skyline",
    caption: "Denver’s skyline with the Rockies in the background!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Denver on Google Maps",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3
  },
  {
    id: "breckenridge-2024-12-01",
    title: "Skiing in Breckenridge",
    date: new Date('2024-12-01T00:00:00Z'),
    timelineHighlight: "Breckenridge Slopes",
    tags: ["skiing", "mountains"],
    snippet: "Hit the snowy slopes of Breckenridge for an epic skiing adventure.",
    image: "attachment://placeholder-breckenridge.jpg",
    imageAlt: "Breckenridge Slopes",
    caption: "Shredding the slopes in Breckenridge!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Breckenridge on Google Maps",
    fullLink: "#",
    location: { lat: 39.4817, lng: -106.0384, name: "Breckenridge, Colorado" },
    stayDuration: 30
  },
  {
    id: "miami-beach-2024-12-30",
    title: "Miami Beach Winter Escape",
    date: new Date('2024-12-30T00:00:00Z'),
    timelineHighlight: "Miami Beach Winter",
    tags: ["beach", "nightlife"],
    snippet: "Escaped winter with sunny days and vibrant nights in Miami Beach.",
    image: "attachment://placeholder-miami-beach.jpg",
    imageAlt: "Miami Beach Winter",
    caption: "Winter sun in Miami Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami Beach on Google Maps",
    fullLink: "miami-beach-2024-12-30.html",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 34
  },
  {
    id: "st-petersburg-2025-02-02",
    title: "St. Petersburg’s Winter Glow",
    date: new Date('2025-02-02T00:00:00Z'),
    timelineHighlight: "St. Petersburg Winter",
    tags: ["beach", "art"],
    snippet: "Enjoyed winter warmth and art-filled streets in St. Petersburg.",
    image: "attachment://placeholder-st-petersburg.jpg",
    imageAlt: "St. Petersburg Winter",
    caption: "Winter vibes in St. Petersburg!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find St. Petersburg on Google Maps",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 5
  },
  {
    id: "sao-paulo-2025-02-07",
    title: "Urban Energy in São Paulo",
    date: new Date('2025-02-07T00:00:00Z'),
    timelineHighlight: "São Paulo Culture",
    tags: ["city", "culture"],
    snippet: "Immersed in São Paulo’s bustling streets, street art, and vibrant food scene.",
    image: "attachment://placeholder-sao-paulo.jpg",
    imageAlt: "São Paulo Skyline",
    caption: "São Paulo’s urban jungle!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find São Paulo on Google Maps",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 9
  },
  {
    id: "rio-de-janeiro-2025-02-16",
    title: "Carnival Vibes in Rio de Janeiro",
    date: new Date('2025-02-16T00:00:00Z'),
    timelineHighlight: "Rio Beaches",
    tags: ["beach", "culture"],
    snippet: "Danced to samba rhythms and relaxed on Copacabana Beach in Rio.",
    image: "attachment://placeholder-rio.jpg",
    imageAlt: "Rio Copacabana",
    caption: "Copacabana Beach in Rio de Janeiro!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Rio de Janeiro on Google Maps",
    fullLink: "#",
    location: { lat: -22.9068, lng: -43.1729, name: "Rio de Janeiro, Brazil" },
    stayDuration: 11
  },
  {
    id: "sao-paulo-2025-02-27",
    title: "Back to São Paulo’s Beat",
    date: new Date('2025-02-27T00:00:00Z'),
    timelineHighlight: "São Paulo Art",
    tags: ["city", "art"],
    snippet: "Returned to São Paulo for more street art and vibrant nightlife.",
    image: "attachment://placeholder-sao-paulo.jpg",
    imageAlt: "São Paulo Street Art",
    caption: "São Paulo’s colorful street art scene!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find São Paulo on Google Maps",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 10
  },
  {
    id: "st-petersburg-2025-03-09",
    title: "Spring in St. Petersburg",
    date: new Date('2025-03-09T00:00:00Z'),
    timelineHighlight: "St. Petersburg Spring",
    tags: ["beach", "art"],
    snippet: "Welcomed spring with beach days and art walks in St. Petersburg.",
    image: "attachment://placeholder-st-petersburg.jpg",
    imageAlt: "St. Petersburg Spring",
    caption: "Springtime in St. Petersburg!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find St. Petersburg on Google Maps",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 44
  },
  {
    id: "williston-2025-03-13",
    title: "Diving Devil’s Den in Williston",
    date: new Date('2025-03-13T00:00:00Z'),
    timelineHighlight: "Devil’s Den Spring",
    tags: ["nature", "adventure"],
    snippet: "Dove into the crystal-clear waters of Devil’s Den Prehistoric Spring for an unforgettable adventure.",
    image: "attachment://placeholder-williston.jpg",
    imageAlt: "Devil’s Den Spring",
    caption: "Exploring the depths of Devil’s Den!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Williston on Google Maps",
    fullLink: "#",
    location: { lat: 29.4086, lng: -82.4757, name: "Williston, Florida" },
    stayDuration: 1
  },
  {
    id: "chicago-2025-03-29",
    title: "Spring Vibes in Chicago",
    date: new Date('2025-03-29T00:00:00Z'),
    timelineHighlight: "Chicago Spring",
    tags: ["city", "culture"],
    snippet: "Embraced Chicago’s spring energy, visiting Paylocity and exploring the city’s vibrant neighborhoods.",
    image: "attachment://placeholder-chicago.jpg",
    imageAlt: "Chicago Spring",
    caption: "Chicago’s springtime charm!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Chicago on Google Maps",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 5
  },
  {
    id: "destin-2025-04-22",
    title: "More Destin Beach Days",
    date: new Date('2025-04-22T00:00:00Z'),
    timelineHighlight: "Destin Beaches",
    tags: ["beach volleyball", "beach"],
    snippet: "Back to Destin for more volleyball and emerald-green beach days.",
    image: "attachment://placeholder-destin.jpg",
    imageAlt: "Destin Beach",
    caption: "Destin’s emerald waters calling!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Destin on Google Maps",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 6
  },
  {
    id: "new-orleans-2025-04-28",
    title: "Jazz and Beignets in New Orleans",
    date: new Date('2025-04-28T00:00:00Z'),
    timelineHighlight: "New Orleans Jazz",
    tags: ["live music", "food"],
    snippet: "Soaked in the vibrant jazz scene and savored beignets in the French Quarter.",
    image: "attachment://placeholder-new-orleans.jpg",
    imageAlt: "New Orleans French Quarter",
    caption: "Jazz on the streets of New Orleans!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find New Orleans on Google Maps",
    fullLink: "#",
    location: { lat: 29.9511, lng: -90.0715, name: "New Orleans, Louisiana" },
    stayDuration: 3
  },
  {
    id: "houston-2025-05-01",
    title: "Urban Exploration in Houston",
    date: new Date('2025-05-01T00:00:00Z'),
    timelineHighlight: "Houston Culture",
    tags: ["city", "culture"],
    snippet: "Explored Houston’s museums and vibrant food scene in a quick city stop.",
    image: "attachment://placeholder-houston.jpg",
    imageAlt: "Houston Skyline",
    caption: "Houston’s skyline shining bright!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Houston on Google Maps",
    fullLink: "#",
    location: { lat: 29.7604, lng: -95.3698, name: "Houston, Texas" },
    stayDuration: 1
  },
  {
    id: "austin-2025-05-02",
    title: "An Epic Day Vibing in Austin",
    date: new Date('2025-05-02T00:00:00Z'),
    timelineHighlight: "Austin Volleyball",
    tags: ["beach volleyball", "coffee"],
    snippet: "From a double espresso with a jaw-dropping skyline view to spiking volleyballs, Austin delivered energy and vibes.",
    image: "attachment://cosmic-skyline.jpg",
    imageAlt: "Austin Skyline from Cosmic Coffee",
    caption: "The breathtaking view of downtown Austin from Cosmic Coffee!",
    mapLink: "https://maps.app.goo.gl/5gKqL9nL8J3mX5zK7",
    mapText: "📍 Find Cosmic Coffee on Google Maps",
    fullLink: "#",
    location: { lat: 30.2672, lng: -97.7431, name: "Austin, Texas" },
    stayDuration: 10
  },
  {
    id: "boulder-2025-05-13",
    title: "Chasing Vibes in Boulder",
    date: new Date('2025-05-13T00:00:00Z'),
    timelineHighlight: "Coffee & Music in Boulder",
    tags: ["coffee", "live music", "wellness"],
    snippet: "Soaking up Boulder’s chill vibes with live music at Trident, unique tonics at Tonic Alchemy Lounge, and daily recovery at the Rec Center.",
    image: "attachment://placeholder-boulder.jpg",
    imageAlt: "Trident Booksellers & Café in Boulder",
    caption: "Catching a live band at Trident Booksellers & Café!",
    mapLink: "https://maps.app.goo.gl/7zZ9kL5nJ3mX5zK7",
    mapText: "📍 Find Boulder on Google Maps",
    fullLink: "boulder-2025-05-17.html",
    location: { lat: 40.0150, lng: -105.2705, name: "Boulder, Colorado" },
    stayDuration: 7
  },
  {
    id: "san-diego-2025-05-20",
    title: "San Diego Whirlwind: Yoga, Thai, and Line Dancing",
    date: new Date('2025-05-20T00:00:00Z'),
    timelineHighlight: "San Diego Line Dancing",
    tags: ["yoga", "friends", "line dancing", "food"],
    snippet: "Landed in San Diego, picked up by Wouter for hot yoga at Indie Yoga, regional pad Thai at Pad Thai Stand, and country line dancing at Moonshine Beach with Wouter and Ray dancing rebelliously in the middle—Ray’s punctuality ensured a smooth airport send-off.",
    image: "attachment://san-diego-user-photo.jpg",
    imageAlt: "Wouter and Ray dancing in the middle of the dancefloor at Moonshine Beach",
    caption: "Wouter and Ray stealing the show at Moonshine Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find San Diego on Google Maps",
    fullLink: "san-diego-2025-05-20.html",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 1
  },
  {
    id: "fort-lauderdale-2025-05-21",
    title: "Volleyball and Vibes in Fort Lauderdale",
    date: new Date('2025-05-21T00:00:00Z'),
    timelineHighlight: "Fort Lauderdale Volleyball",
    tags: ["beach", "beach volleyball", "friends"],
    snippet: "Arrived in Fort Lauderdale after a Denver layover, staying with Bartek for work, beach volleyball in Deerfield, and a relaxing massage together.",
    image: "attachment://placeholder-fort-lauderdale.jpg",
    imageAlt: "Beach volleyball game in Deerfield with Bartek",
    caption: "Ready to spike with Bartek in Deerfield!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Fort Lauderdale on Google Maps",
    fullLink: "fort-lauderdale-2025-05-21.html",
    location: { lat: 26.1224, lng: -80.1373, name: "Fort Lauderdale, Florida" },
    stayDuration: 2
  },
  {
    id: "miami-beach-2025-05-23",
    title: "South Beach Volleyball with Friends",
    date: new Date('2025-05-23T00:00:00Z'),
    timelineHighlight: "South Beach Volleyball",
    tags: ["beach", "beach volleyball", "nightlife", "friends"],
    snippet: "Played high-energy volleyball with Wouter and locals at Ocean and 8th Street, renewed my Global Entry, and soaked up South Beach’s vibe.",
    image: "attachment://placeholder-miami-beach.jpg",
    imageAlt: "Miami Beach Volleyball",
    caption: "Volleyball action on South Beach!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Miami Beach on Google Maps",
    fullLink: "#",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7
  },
  {
    id: "tampa-2025-05-30",
    title: "Tampa Stop for Hawaii Prep",
    date: new Date('2025-05-30T00:00:00Z'),
    timelineHighlight: "Tampa Relocation",
    tags: ["travel", "relocation"],
    snippet: "Spent a weekend in Tampa picking up luggage for my big move to Hawaii, with a side of waterfront views.",
    image: "attachment://placeholder-tampa.jpg",
    imageAlt: "Tampa Waterfront",
    caption: "Tampa’s waterfront during my relocation prep!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Tampa on Google Maps",
    fullLink: "#",
    location: { lat: 27.9506, lng: -82.4572, name: "Tampa, Florida" },
    stayDuration: 3
  },
  {
    id: "san-diego-2025-06-01",
    title: "San Diego Coastal Reset",
    date: new Date('2025-06-01T00:00:00Z'),
    timelineHighlight: "San Diego Beaches",
    tags: ["beach", "surfing"],
    snippet: "Returned to San Diego for two weeks of surfing, beach vibes, and prepping for the Hawaii move.",
    image: "attachment://placeholder-san-diego.jpg",
    imageAlt: "San Diego Beach",
    caption: "Riding the waves in San Diego!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find San Diego on Google Maps",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 14
  },
  {
    id: "oahu-2025-06-15",
    title: "New Beginnings in Oahu",
    date: new Date('2025-06-15T00:00:00Z'),
    timelineHighlight: "Oahu New Home",
    tags: ["beach", "nature", "relocation"],
    snippet: "Kicked off my new chapter in Oahu, settling into island life with beaches and volcanic trails.",
    image: "attachment://placeholder-oahu.jpg",
    imageAlt: "Oahu Beach",
    caption: "Starting fresh on Oahu’s shores!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Oahu on Google Maps",
    fullLink: "#",
    location: { lat: 21.4389, lng: -158.0001, name: "Oahu, Hawaii" },
    stayDuration: 110
  },
  {
    id: "chicago-2025-10-03",
    title: "Chicago’s Fall Charm",
    date: new Date('2025-10-03T00:00:00Z'),
    timelineHighlight: "Chicago Fall",
    tags: ["city", "culture"],
    snippet: "Returned to Chicago for fall vibes, art walks, and cozy coffee shops.",
    image: "attachment://placeholder-chicago.jpg",
    imageAlt: "Chicago Fall",
    caption: "Chicago’s fall colors by the lake!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Chicago on Google Maps",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 5
  },
  {
    id: "canggu-2025-10-24",
    title: "Surf and Serenity in Canggu",
    date: new Date('2025-10-24T00:00:00Z'),
    timelineHighlight: "Canggu Surf",
    tags: ["beach", "surfing"],
    snippet: "Surfed Canggu’s waves and found peace in Bali’s rice fields and cafes.",
    image: "attachment://placeholder-canggu.jpg",
    imageAlt: "Canggu Beach",
    caption: "Canggu’s laid-back surf vibes!",
    mapLink: "https://maps.app.goo.gl/placeholder",
    mapText: "📍 Find Canggu on Google Maps",
    fullLink: "#",
    location: { lat: -8.6596, lng: 115.1326, name: "Canggu, Indonesia" },
    stayDuration: 21
  }
].sort((a, b) => a.date - b.date);