// Helper function to format duration
function formatDuration(days) {
  if (days >= 365) {
    const years = Math.floor(days / 365);
    const remainingDays = days % 365;
    return `${years} year${years > 1 ? 's' : ''}${remainingDays > 0 ? ` and ${remainingDays} day${remainingDays > 1 ? 's' : ''}` : ''}`;
  } else if (days >= 90) {
    const months = Math.floor(days / 30);
    const remainingDays = days % 30;
    return `${months} month${months > 1 ? 's' : ''}${remainingDays > 0 ? ` and ${remainingDays} day${remainingDays > 1 ? 's' : ''}` : ''}`;
  } else {
    return `${days} day${days > 1 ? 's' : ''}`;
  }
}

window.momentsInTime = [
  {
    id: "varna-1988-11-24",
    title: "Growing Up in Varna",
    date: new Date('1988-11-24T00:00:00Z'),
    timelineHighlight: "Varna Childhood",
    tags: ["beach", "culture"],
    snippet: "Spent my early years in Varna, playing on Black Sea beaches and soaking in Bulgarian culture.",
    fullLink: "#",
    location: { lat: 43.2141, lng: 27.9147, name: "Varna, Bulgaria" },
    stayDuration: 2190,
    formattedDuration: formatDuration(2190)
  },
  {
    id: "sofia-1994-11-24",
    title: "Wild Teenage Years in Sofia",
    date: new Date('1994-11-24T00:00:00Z'),
    timelineHighlight: "Sofia Youth",
    tags: ["city", "culture", "sports", "education"],
    snippet: "Started at 119th High School at age 6, where I spent grades 1-6. Later transferred to Doris Tenedi German High School for grades 7-10, balancing my studies with an adventurous social life. By 13, I was already exploring Sofia's nightlife, hanging out downtown with friends, and playing intense street soccer on concrete courts - the scars on my knees still tell those stories. Those early teenage years in Sofia shaped my adventurous spirit.",
    fullLink: "2005/03-20-sofia-childhood.html",
    location: { lat: 42.6977, lng: 23.3219, name: "Sofia, Bulgaria" },
    stayDuration: 3650,
    formattedDuration: formatDuration(3650),
    image: "attachment://2005/03-20-sofia-childhood.jpg",
    imageAlt: "Young Paul in Sofia",
    caption: "Exploring the streets of Sofia as a young boy",
    popoverImageStyle: {
      objectFit: "contain",
      objectPosition: "center",
      borderRadius: "0"
    }
  },
  {
    id: "osseo-2004-08-01",
    title: "Exchange Year in Osseo",
    date: new Date('2004-08-01T00:00:00Z'),
    timelineHighlight: "Osseo Exchange",
    tags: ["culture", "education"],
    snippet: "Lived with a foster family in Osseo, Wisconsin, diving into American high school life at Osseo-Fairchild.",
    fullLink: "#",
    location: { lat: 44.5722, lng: -91.2271, name: "Osseo, Wisconsin" },
    stayDuration: 180,
    formattedDuration: formatDuration(180)
  },
  {
    id: "chicago-2005-02-01",
    title: "Chicago: High School, College & Volleyball Beginnings",
    date: new Date('2005-02-01T00:00:00Z'),
    timelineHighlight: "Chicago Life",
    tags: ["city", "education", "sports", "relationships"],
    snippet: "Transferred to Gordon Tech, graduated high school, attended college, met my ex-wife, and started my volleyball journey at 18 - a transformative decade in the Windy City.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 3650,
    formattedDuration: formatDuration(3650)
  },
  {
    id: "medellin-2022-07-02",
    title: "Exploring Medellín's Markets",
    date: new Date('2022-07-02T00:00:00Z'),
    timelineHighlight: "Medellín Markets",
    tags: ["culture", "city"],
    snippet: "Wandered through Medellín's bustling markets, soaking in the local vibes at Homecenter and beyond.",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 30,
    formattedDuration: formatDuration(30)
  },
  {
    id: "medellin-2022-11-01",
    title: "Vibrant Streets of Medellín",
    date: new Date('2022-11-01T00:00:00Z'),
    timelineHighlight: "Medellín Culture",
    tags: ["culture", "city"],
    snippet: "Dived into the colorful streets of Medellín, from Comuna 13's street art to lively salsa nights.",
    fullLink: "#",
    location: { lat: 6.2442, lng: -75.5812, name: "Medellín, Colombia" },
    stayDuration: 60,
    formattedDuration: formatDuration(60)
  },
  {
    id: "st-petersburg-2023-01-01",
    title: "Sun and Art in St. Petersburg",
    date: new Date('2023-01-01T00:00:00Z'),
    timelineHighlight: "St. Petersburg Art",
    tags: ["beach", "art"],
    snippet: "Soaked up the sun and explored vibrant murals in St. Petersburg's artsy downtown.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 217,
    formattedDuration: formatDuration(217)
  },
  {
    id: "miami-2023-08-07",
    title: "Beaches and Beats in Miami",
    date: new Date('2023-08-07T00:00:00Z'),
    timelineHighlight: "Miami Nightlife",
    tags: ["beach", "nightlife"],
    snippet: "Danced to the beats and relaxed on the vibrant beaches of South Beach, Miami.",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "beirut-2023-08-09",
    title: "History and Vibes in Beirut",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Beirut Culture",
    tags: ["culture", "history"],
    snippet: "Explored Beirut's historic souks and vibrant nightlife along the Mediterranean coast.",
    fullLink: "#",
    location: { lat: 33.8938, lng: 35.5018, name: "Beirut, Lebanon" },
    stayDuration: 8,
    formattedDuration: formatDuration(8)
  },
  {
    id: "baalbek-2023-08-09",
    title: "Ancient Ruins in Baalbek",
    date: new Date('2023-08-09T00:00:00Z'),
    timelineHighlight: "Baalbek Ruins",
    tags: ["history", "culture"],
    snippet: "Explored the majestic Temple of Bacchus in Baalbek, a stunning journey into Lebanon's ancient past.",
    fullLink: "#",
    location: { lat: 34.0069, lng: 36.2039, name: "Baalbek, Lebanon" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "athens-2023-08-18",
    title: "Ancient Wonders in Athens",
    date: new Date('2023-08-18T00:00:00Z'),
    timelineHighlight: "Athens History",
    tags: ["history", "culture"],
    snippet: "Walked through history at the Acropolis and savored Greek flavors in Plaka.",
    fullLink: "#",
    location: { lat: 37.9838, lng: 23.7275, name: "Athens, Greece" },
    stayDuration: 3,
    formattedDuration: formatDuration(3)
  },
  {
    id: "barcelona-2023-08-21",
    title: "Art and Architecture in Barcelona",
    date: new Date('2023-08-21T00:00:00Z'),
    timelineHighlight: "Barcelona Art",
    tags: ["art", "architecture"],
    snippet: "Marveled at Gaudí's masterpieces and strolled along La Rambla in vibrant Barcelona.",
    fullLink: "#",
    location: { lat: 41.3851, lng: 2.1734, name: "Barcelona, Spain" },
    stayDuration: 23,
    formattedDuration: formatDuration(23)
  },
  {
    id: "sofia-2023-09-13",
    title: "Hidden Gems in Sofia",
    date: new Date('2023-09-13T00:00:00Z'),
    timelineHighlight: "Sofia Culture",
    tags: ["culture", "history"],
    snippet: "Discovered Sofia's historic churches and vibrant markets in Bulgaria's capital.",
    fullLink: "#",
    location: { lat: 42.6977, lng: 23.3219, name: "Sofia, Bulgaria" },
    stayDuration: 38,
    formattedDuration: formatDuration(38)
  },
  {
    id: "dubai-2023-10-05",
    title: "Luxury and Adventure in Dubai",
    date: new Date('2023-10-05T00:00:00Z'),
    timelineHighlight: "Dubai Skyline",
    tags: ["city", "luxury"],
    snippet: "Admired Dubai's towering skyline and explored the desert dunes on an epic adventure.",
    fullLink: "#",
    location: { lat: 25.2048, lng: 55.2708, name: "Dubai, United Arab Emirates" },
    stayDuration: 4,
    formattedDuration: formatDuration(4)
  },
  {
    id: "varna-2023-10-18",
    title: "Black Sea Bliss in Varna",
    date: new Date('2023-10-18T00:00:00Z'),
    timelineHighlight: "Varna Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Varna's Black Sea beaches and explored its ancient Roman baths.",
    fullLink: "#",
    location: { lat: 43.2141, lng: 27.9147, name: "Varna, Bulgaria" },
    stayDuration: 39,
    formattedDuration: formatDuration(39)
  },
  {
    id: "chattanooga-2024-05-14",
    title: "Outdoor Vibes in Chattanooga",
    date: new Date('2024-05-14T00:00:00Z'),
    timelineHighlight: "Chattanooga Trails",
    tags: ["hiking", "nature"],
    snippet: "Hiked scenic trails and explored the vibrant riverfront in Chattanooga.",
    fullLink: "#",
    location: { lat: 35.0456, lng: -85.3097, name: "Chattanooga, Tennessee" },
    stayDuration: 5,
    formattedDuration: formatDuration(5)
  },
  {
    id: "st-petersburg-2024-05-19",
    title: "Back to St. Petersburg's Shores",
    date: new Date('2024-05-19T00:00:00Z'),
    timelineHighlight: "St. Petersburg Beaches",
    tags: ["beach", "art"],
    snippet: "Returned to St. Petersburg for more beach vibes and local art galleries.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 12,
    formattedDuration: formatDuration(12)
  },
  {
    id: "chicago-2024-06-01",
    title: "Windy City Adventures in Chicago",
    date: new Date('2024-06-01T00:00:00Z'),
    timelineHighlight: "Chicago Skyline",
    tags: ["city", "culture"],
    snippet: "Explored Chicago's iconic skyline, deep-dish pizza, and vibrant art scene.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 60,
    formattedDuration: formatDuration(60)
  },
  {
    id: "clearwater-2024-08-01",
    title: "Sunsets in Clearwater",
    date: new Date('2024-08-01T00:00:00Z'),
    timelineHighlight: "Clearwater Beaches",
    tags: ["beach", "nature"],
    snippet: "Chased epic sunsets and relaxed on the white sands of Clearwater Beach.",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 6,
    formattedDuration: formatDuration(6)
  },
  {
    id: "miami-beach-2024-08-08",
    title: "Vibrant Miami Beach",
    date: new Date('2024-08-08T00:00:00Z'),
    timelineHighlight: "Miami Beach Vibes",
    tags: ["beach", "nightlife"],
    snippet: "Soaked up the sun and danced through the night in Miami Beach's lively scene.",
    fullLink: "#",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  {
    id: "hermosa-beach-2024-08-15",
    title: "Chill Vibes in Hermosa Beach",
    date: new Date('2024-08-15T00:00:00Z'),
    timelineHighlight: "Hermosa Beach Surf",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and enjoyed laid-back vibes on Hermosa Beach's sunny shores.",
    fullLink: "#",
    location: { lat: 33.8622, lng: -118.3995, name: "Hermosa Beach, California" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  {
    id: "san-diego-2024-08-22",
    title: "Surf and Sun in San Diego",
    date: new Date('2024-08-22T00:00:00Z'),
    timelineHighlight: "San Diego Surfing",
    tags: ["beach", "surfing"],
    snippet: "Caught waves and soaked up the sun on San Diego's beautiful beaches.",
    fullLink: "#",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 9,
    formattedDuration: formatDuration(9)
  },
  {
    id: "honolulu-2024-09-01",
    title: "Island Life in Honolulu",
    date: new Date('2024-09-01T00:00:00Z'),
    timelineHighlight: "Honolulu Beaches",
    tags: ["beach", "nature"],
    snippet: "Embraced island life in Honolulu with stunning beaches and lush hikes.",
    fullLink: "#",
    location: { lat: 21.3069, lng: -157.8583, name: "Honolulu, Hawaii" },
    stayDuration: 38,
    formattedDuration: formatDuration(38)
  },
  {
    id: "st-petersburg-2024-10-10",
    title: "St. Petersburg's Coastal Charm",
    date: new Date('2024-10-10T00:00:00Z'),
    timelineHighlight: "St. Petersburg Sunsets",
    tags: ["beach", "art"],
    snippet: "Back again to St. Petersburg for coastal sunsets and local art vibes.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 6,
    formattedDuration: formatDuration(6)
  },
  {
    id: "destin-2024-10-16",
    title: "Beach Volleyball in Destin",
    date: new Date('2024-10-16T00:00:00Z'),
    timelineHighlight: "Destin Volleyball",
    tags: ["beach volleyball", "beach"],
    snippet: "Kicked off with sun, sand, and epic volleyball matches in Destin's emerald waters.",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 5,
    formattedDuration: formatDuration(5)
  },
  {
    id: "miami-2024-10-23",
    title: "Miami's Electric Energy",
    date: new Date('2024-10-23T00:00:00Z'),
    timelineHighlight: "Miami Beaches",
    tags: ["beach", "nightlife"],
    snippet: "Returned to Miami for more beach days and electric nightlife in South Beach.",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 8,
    formattedDuration: formatDuration(8)
  },
  {
    id: "playa-del-carmen-2024-11-01",
    title: "Mayan Riviera Magic in Playa del Carmen",
    date: new Date('2024-11-01T00:00:00Z'),
    timelineHighlight: "Playa del Carmen Beaches",
    tags: ["beach", "culture"],
    snippet: "Relaxed on Playa del Carmen's beaches and explored nearby Mayan ruins.",
    fullLink: "#",
    location: { lat: 20.6296, lng: -87.0739, name: "Playa del Carmen, Mexico" },
    stayDuration: 14,
    formattedDuration: formatDuration(14)
  },
  {
    id: "clearwater-2024-11-16",
    title: "More Clearwater Sunsets",
    date: new Date('2024-11-16T00:00:00Z'),
    timelineHighlight: "Clearwater Sunsets",
    tags: ["beach", "nature"],
    snippet: "Back to Clearwater for more stunning sunsets and beach relaxation.",
    fullLink: "#",
    location: { lat: 27.9659, lng: -82.8001, name: "Clearwater, Florida" },
    stayDuration: 12,
    formattedDuration: formatDuration(12)
  },
  {
    id: "denver-2024-11-20",
    title: "Denver's Urban Pulse",
    date: new Date('2024-11-20T00:00:00Z'),
    timelineHighlight: "Denver City",
    tags: ["city", "culture"],
    snippet: "Dove into Denver's vibrant urban scene, exploring Broadway and the city's eclectic neighborhoods.",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3,
    formattedDuration: formatDuration(3)
  },
  {
    id: "denver-2024-11-28",
    title: "Rocky Mountain High in Denver",
    date: new Date('2024-11-28T00:00:00Z'),
    timelineHighlight: "Denver Trails",
    tags: ["hiking", "city"],
    snippet: "Explored Denver's urban charm and took in stunning views from nearby trails.",
    fullLink: "#",
    location: { lat: 39.7392, lng: -104.9903, name: "Denver, Colorado" },
    stayDuration: 3,
    formattedDuration: formatDuration(3)
  },
  {
    id: "breckenridge-2024-12-01",
    title: "Skiing in Breckenridge",
    date: new Date('2024-12-01T00:00:00Z'),
    timelineHighlight: "Breckenridge Slopes",
    tags: ["skiing", "mountains"],
    snippet: "Hit the snowy slopes of Breckenridge for an epic skiing adventure.",
    fullLink: "#",
    location: { lat: 39.4817, lng: -106.0384, name: "Breckenridge, Colorado" },
    stayDuration: 30,
    formattedDuration: formatDuration(30)
  },
  {
    id: "miami-beach-2024-12-30",
    title: "Miami Beach Winter Escape",
    date: new Date('2024-12-30T00:00:00Z'),
    timelineHighlight: "Miami Beach Winter",
    tags: ["beach", "nightlife"],
    snippet: "Escaped winter with sunny days and vibrant nights in Miami Beach.",
    fullLink: "2024/12-30-miami-beach.html",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 34,
    formattedDuration: formatDuration(34)
  },
  {
    id: "st-petersburg-2025-02-02",
    title: "St. Petersburg's Winter Glow",
    date: new Date('2025-02-02T00:00:00Z'),
    timelineHighlight: "St. Petersburg Winter",
    tags: ["beach", "art"],
    snippet: "Enjoyed winter warmth and art-filled streets in St. Petersburg.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 5,
    formattedDuration: formatDuration(5)
  },
  {
    id: "sao-paulo-2025-02-07",
    title: "Urban Energy in São Paulo",
    date: new Date('2025-02-07T00:00:00Z'),
    timelineHighlight: "São Paulo Culture",
    tags: ["city", "culture"],
    snippet: "Immersed in São Paulo's bustling streets, street art, and vibrant food scene.",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 9,
    formattedDuration: formatDuration(9)
  },
  {
    id: "rio-de-janeiro-2025-02-16",
    title: "Carnival Vibes in Rio de Janeiro",
    date: new Date('2025-02-16T00:00:00Z'),
    timelineHighlight: "Rio Beaches",
    tags: ["beach", "culture"],
    snippet: "Danced to samba rhythms and relaxed on Copacabana Beach in Rio.",
    fullLink: "#",
    location: { lat: -22.9068, lng: -43.1729, name: "Rio de Janeiro, Brazil" },
    stayDuration: 11,
    formattedDuration: formatDuration(11)
  },
  {
    id: "sao-paulo-2025-02-27",
    title: "Back to São Paulo's Beat",
    date: new Date('2025-02-27T00:00:00Z'),
    timelineHighlight: "São Paulo Art",
    tags: ["city", "art"],
    snippet: "Returned to São Paulo for more street art and vibrant nightlife.",
    fullLink: "#",
    location: { lat: -23.5505, lng: -46.6333, name: "São Paulo, Brazil" },
    stayDuration: 10,
    formattedDuration: formatDuration(10)
  },
  {
    id: "st-petersburg-2025-03-09",
    title: "Spring in St. Petersburg",
    date: new Date('2025-03-09T00:00:00Z'),
    timelineHighlight: "St. Petersburg Spring",
    tags: ["beach", "art"],
    snippet: "Welcomed spring with beach days and art walks in St. Petersburg.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 44,
    formattedDuration: formatDuration(44)
  },
  {
    id: "williston-2025-03-13",
    title: "Diving Devil's Den in Williston",
    date: new Date('2025-03-13T00:00:00Z'),
    timelineHighlight: "Devil's Den Spring",
    tags: ["nature", "adventure"],
    snippet: "Dove into the crystal-clear waters of Devil's Den Prehistoric Spring for an unforgettable adventure.",
    fullLink: "#",
    location: { lat: 29.4086, lng: -82.4757, name: "Williston, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "chicago-2025-03-29",
    title: "Spring Vibes in Chicago",
    date: new Date('2025-03-29T00:00:00Z'),
    timelineHighlight: "Chicago Spring",
    tags: ["city", "culture"],
    snippet: "Embraced Chicago's spring energy, visiting Paylocity and exploring the city's vibrant neighborhoods.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 5,
    formattedDuration: formatDuration(5)
  },
  {
    id: "destin-2025-04-22",
    title: "More Destin Beach Days",
    date: new Date('2025-04-22T00:00:00Z'),
    timelineHighlight: "Destin Beaches",
    tags: ["beach volleyball", "beach"],
    snippet: "Back to Destin for more volleyball and emerald-green beach days.",
    fullLink: "#",
    location: { lat: 30.3935, lng: -86.4958, name: "Destin, Florida" },
    stayDuration: 6,
    formattedDuration: formatDuration(6)
  },
  {
    id: "new-orleans-2025-04-28",
    title: "Jazz and Beignets in New Orleans",
    date: new Date('2025-04-28T00:00:00Z'),
    timelineHighlight: "New Orleans Jazz",
    tags: ["live music", "food"],
    snippet: "Soaked in the vibrant jazz scene and savored beignets in the French Quarter.",
    fullLink: "#",
    location: { lat: 29.9511, lng: -90.0715, name: "New Orleans, Louisiana" },
    stayDuration: 3,
    formattedDuration: formatDuration(3)
  },
  {
    id: "houston-2025-05-01",
    title: "Urban Exploration in Houston",
    date: new Date('2025-05-01T00:00:00Z'),
    timelineHighlight: "Houston Culture",
    tags: ["city", "culture"],
    snippet: "Explored Houston's museums and vibrant food scene in a quick city stop.",
    fullLink: "#",
    location: { lat: 29.7604, lng: -95.3698, name: "Houston, Texas" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "austin-2025-05-02",
    title: "An Epic Day Vibing in Austin",
    date: new Date('2025-05-02T00:00:00Z'),
    timelineHighlight: "Austin Volleyball",
    tags: ["beach volleyball", "coffee"],
    snippet: "From a double espresso with a jaw-dropping skyline view to spiking volleyballs, Austin delivered energy and vibes.",
    fullLink: "#",
    location: { lat: 30.2672, lng: -97.7431, name: "Austin, Texas" },
    stayDuration: 10,
    formattedDuration: formatDuration(10)
  },
  {
    id: "boulder-2025-05-13",
    title: "Chasing Vibes in Boulder",
    date: new Date('2025-05-13T00:00:00Z'),
    timelineHighlight: "Coffee & Music in Boulder",
    tags: ["coffee", "live music", "wellness"],
    snippet: "Soaking up Boulder's chill vibes with live music at Trident, unique tonics at Tonic Alchemy Lounge, and daily recovery at the Rec Center.",
    fullLink: "2025/05-17-boulder.html",
    location: { lat: 40.0150, lng: -105.2705, name: "Boulder, Colorado" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  {
    id: "san-diego-2025-05-20",
    title: "San Diego Whirlwind: Yoga, Thai, and Line Dancing",
    date: new Date('2025-05-20T00:00:00Z'),
    timelineHighlight: "San Diego Line Dancing",
    tags: ["yoga", "friends", "line dancing", "food"],
    snippet: "Landed in San Diego, picked up by Wouter for hot yoga at Indie Yoga, regional pad Thai at Pad Thai Stand, and country line dancing at Moonshine Beach with Wouter and Ray dancing rebelliously in the middle—Ray's punctuality ensured a smooth airport send-off.",
    fullLink: "2025/05-20-san-diego.html",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "fort-lauderdale-2025-05-21",
    title: "Volleyball and Vibes in Fort Lauderdale",
    date: new Date('2025-05-21T00:00:00Z'),
    timelineHighlight: "Fort Lauderdale Volleyball",
    tags: ["beach", "beach volleyball", "friends"],
    snippet: "Arrived in Fort Lauderdale after a Denver layover, staying with Bartek for work, beach volleyball in Deerfield, and a relaxing massage together.",
    fullLink: "2025/05-21-fort-lauderdale.html",
    location: { lat: 26.1224, lng: -80.1373, name: "Fort Lauderdale, Florida" },
    stayDuration: 2,
    formattedDuration: formatDuration(2)
  },
  {
    id: "miami-beach-2025-05-23",
    title: "South Beach Volleyball, Bachata, and a Drive to St. Pete",
    date: new Date('2025-05-23T00:00:00Z'),
    timelineHighlight: "South Beach Adventures",
    tags: ["beach", "beach volleyball", "nightlife", "friends", "bachata"],
    snippet: "Played high-energy volleyball, danced bachata at Alain's, and drove to St. Pete.",
    fullLink: "2025/05-23-miami-beach.html",
    location: { lat: 25.7907, lng: -80.1300, name: "Miami Beach, Florida" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  {
    id: "tampa-2025-05-30",
    title: "Tampa Weekend: Road Trips, Brazilian Feasts, and St. Pete Yoga Vibes",
    date: new Date('2025-05-30T00:00:00Z'),
    timelineHighlight: "Tampa Bay Vibes",
    tags: ["travel", "yoga", "food", "friends", "relocation"],
    snippet: "Cruised from Miami to St. Pete, feasted at a Brazilian steakhouse, flowed through yoga in St. Petersburg, and recovered in Clearwater while prepping for Hawaii.",
    image: "attachment://2025/05-30-tampa.jpg",
    imageAlt: "Post yoga smoothie",
    caption: "Leigha, Leo & Paul enjoying a smoothie after Yoga",
    fullLink: "2025/05-30-tampa.html",
    location: { lat: 27.9506, lng: -82.4572, name: "Tampa, Florida" },
    stayDuration: 3,
    formattedDuration: formatDuration(3)
  },
  {
    id: "san-diego-2025-06-01",
    title: "Finding Rhythm in San Diego's June Gloom",
    date: new Date('2025-06-01T00:00:00Z'),
    timelineHighlight: "San Diego Life",
    tags: ["beach volleyball", "remote work", "coffee", "culture", "wellness", "friends", "hookah"],
    snippet: "Two weeks of balanced living in San Diego, combining European team meetings, beach volleyball at South Mission, and exploring local gems - all while embracing the city's famous June Gloom.",
    image: "attachment://2025/06-01-san-diego.jpg",
    imageAlt: "Whale watching in San Diego",
    caption: "Taking a break from the routine for some ocean adventures!",
    fullLink: "2025/06-01-san-diego.html",
    location: { lat: 32.7157, lng: -117.1611, name: "San Diego, California" },
    stayDuration: 12,
    formattedDuration: formatDuration(12)
  },
  {
    id: "oahu-2025-06-13",
    title: "New Beginnings in Oahu",
    date: new Date('2025-06-13T00:00:00Z'),
    timelineHighlight: "Oahu New Home",
    tags: ["beach", "nature", "relocation"],
    snippet: "Will launch a new chapter in Oahu, settling into island life with beaches and volcanic trails.",
    fullLink: "#",
    location: { lat: 21.4389, lng: -158.0001, name: "Oahu, Hawaii" },
    stayDuration: 60,
    formattedDuration: formatDuration(60)
  },
  {
    id: "philippines-2025-08-12",
    title: "Reconnecting with Leo & Wellness Center Vision in the Philippines",
    date: new Date('2025-08-12T00:00:00Z'),
    timelineHighlight: "Philippines with Leo",
    tags: ["beach", "culture", "islands", "friends", "wellness", "business"],
    snippet: "Will meet up with Leo in his hometown north of Manila, then head to Siargao to scout potential land for a wellness center featuring beach volleyball, yoga, smoothies, and recovery options like cold plunge, sauna, and steam room.",
    fullLink: "#",
    location: { lat: 12.8797, lng: 121.7740, name: "Philippines" },
    stayDuration: 12,
    formattedDuration: formatDuration(12)
  },
  {
    id: "bangkok-2025-08-24",
    title: "Bangkok Digital Nomad Adventure - The Complete Experience",
    date: new Date('2025-08-24T00:00:00Z'),
    timelineHighlight: "Bangkok Digital Nomad",
    tags: ["culture", "food", "city", "friends", "remote work", "nightlife", "running", "beach volleyball", "wellness", "hookah", "urban runner", "gym", "adult playground", "chicago", "atlanta", "group adventures"],
    snippet: "Epic month-long Bangkok adventure coming to a close! What a journey: Bozhi couldn't make it but Jamie flew in from Maui and absolutely crushed it with me. Then Boy (Leo's brother) and his buddy Sean arrived with a crew of guys from Chicago and Atlanta for incredible group adventures. Solo time was equally amazing - hitting the gym religiously, eating incredible food, and truly living it up in Bangkok, the ultimate adult playground. Logged multiple Urban Runner episodes capturing the city's energy. Bangkok proved why it's #1 for digital nomads - this place has everything.",
    fullLink: "#",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 31,
    formattedDuration: formatDuration(31)
  },
  {
    id: "urban-runner-episode-4-2025-08-31",
    title: "Urban Runner Episode 4: Bangkok Hustle I",
    date: new Date('2025-08-31T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 4",
    tags: ["urban runner", "bangkok hustle", "scam", "wealth redistribution", "volleyball", "bangkok", "gamification"],
    snippet: "Part 1 of the Bangkok Hustle saga - the infamous scam encounter that became Urban Runner's defining moment. A 12-mile journey through Bangkok featuring wealth redistribution (441 THB given back) and the 6,500 THB loss that set up the dramatic confrontation in Episode 5.",
    image: "attachment:///moments/bangkok/2025-08-31/cover.png",
    imageAlt: "Urban Runner Episode 4: Bangkok Hustle I",
    caption: "Bangkok Hustle I - The Setup",
    fullLink: "/moments/bangkok/2025-08-31/",
    contentFile: "/moments/bangkok/2025-08-31/content.html",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "urban-runner-episode-5-2025-09-01",
    title: "Urban Runner Episode 5: Bangkok Hustle II",
    date: new Date('2025-09-01T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 5",
    tags: ["urban runner", "meta gaming", "qr codes", "street justice", "hookah", "cannabis", "work", "gamification"],
    snippet: "A meta gaming masterpiece in Bangkok's Sukhumvit district - 6.5 hours working on Urban Runner while living Urban Runner at Marouch Hookah Lounge, successful QR code test at Thai Cannabis Club, and dramatic confrontation with Episode 4 scammers.",
    image: "attachment:///moments/bangkok/2025-09-01/cover.png",
    imageAlt: "Urban Runner Episode 5: Bangkok Hustle II",
    caption: "Bangkok Hustle II - Side Quest Day",
    fullLink: "/moments/bangkok/2025-09-01/",
    contentFile: "/moments/bangkok/2025-09-01/content.html",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "urban-runner-episode-6-2025-09-02",
    title: "Urban Runner Episode 6: Amsterdam Café Cutscene",
    date: new Date('2025-09-02T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 6",
    tags: ["urban runner", "sewer city", "outdoor gym", "amsterdam cafe", "wealth redistribution", "bangkok", "gamification"],
    snippet: "The wildest Urban Runner episode yet - 13 miles through Sewer City, outdoor gym workouts, El Gaucho tourist tax, Amsterdam Café cutscene, and late-night Decathlon shopping. Proved that Urban Runner could handle multiple storylines and urban exploration in a single day.",
    image: "attachment:///moments/bangkok/2025-09-02/cover.png",
    imageAlt: "Urban Runner Episode 6: Amsterdam Café Cutscene",
    caption: "Amsterdam Café Cutscene - Night Adventures",
    fullLink: "/moments/bangkok/2025-09-02/",
    contentFile: "/moments/bangkok/2025-09-02/content.html",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "urban-runner-episode-7-2025-09-03",
    title: "Urban Runner Episode 7: Pura Vida",
    date: new Date('2025-09-03T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 7",
    tags: ["urban runner", "pura vida", "k-fit", "volleyball", "spa reset", "market detour", "bangkok", "recovery"],
    snippet: "Episode 7: Pura Vida - A journey through Bangkok featuring K-FIT power-ups, market detours with Havana flashbacks, volleyball victories at Pura Vida, and complete recovery at Let's Relax Spa. Blended athletic victories, cultural immersion, and personal recovery while carrying the K-FIT vision forward.",
      image: "attachment:///moments/bangkok/2025-09-03/cover.png",
    imageAlt: "Urban Runner Episode 7: Pura Vida",
    caption: "Pura Vida Victory - K-FIT Vision Forward",
    fullLink: "/moments/bangkok/2025-09-03/",
    contentFile: "/moments/bangkok/2025-09-03/content.html",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "urban-runner-episode-13-2025-09-09",
    title: "Urban Runner Episode 13: Bangkok Green Lung & City Cross",
    date: new Date('2025-09-09T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 13",
    tags: ["urban runner", "bangkok green lung", "nature", "city exploration", "bike adventure", "wildlife", "massage", "piano academy", "amsterdam cafe", "latin dancing", "interactive cards"],
    snippet: "Episode 13: Bangkok Green Lung & City Cross - An interactive Tinder-style card journey through Bangkok's hidden jungle island and back to urban chaos. Features 32 swipeable checkpoint cards, wildlife encounters, bike adventures through Bang Kachao, piano academy detours, and late-night Latin dancing.",
    image: "attachment:///moments/bangkok/2025-09-09/cover.png",
    imageAlt: "Urban Runner Episode 13: Bangkok Green Lung & City Cross",
    caption: "Bangkok Green Lung Serenity - Interactive Card Adventure",
    fullLink: "/moments/bangkok/2025-09-09/",
    contentFile: "/moments/bangkok/2025-09-09/data.json",
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1),
    isInteractive: true
  },
  {
    id: "urban-runner-episode-15-2025-09-11",
    title: "Urban Runner Episode 15: Dinner Date",
    date: new Date('2025-09-11T00:00:00Z'),
    timelineHighlight: "Bangkok Ep 15",
    tags: ["urban runner", "dinner date", "bangkok", "rooftop", "tichuca", "bts", "nann", "ava brasserie", "interactive cards"],
    snippet: "Episode 15: Dinner Date - A day of balance between coding grind and human connection. From publishing Episode 13 in the new card-swipe format to rooftop meditation, work sync calls, dinner with Nann at AVA Brasserie, and finally experiencing Bangkok's BTS train system for the first time.",
    image: "attachment:///moments/bangkok/2025-09-11/cover.png",
    imageAlt: "Urban Runner Episode 15: Dinner Date",
    caption: "Dinner Date - Interactive Card Adventure",
    fullLink: "/moments/bangkok/2025-09-11/",
    contentFile: "/moments/bangkok/2025-09-11/data.json",
    isInteractive: true,
    location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
    {
      id: "urban-runner-episode-20-2025-09-16",
      title: "Urban Runner Episode 20: Comic Book Edition",
      date: new Date('2025-09-16T00:00:00Z'),
      timelineHighlight: "Bangkok Ep 20",
      tags: ["urban runner", "comic book", "bangkok", "digital storytelling", "innovation", "turn.js", "flipbook"],
      snippet: "Episode 20: Comic Book Edition - A revolutionary shift in Urban Runner storytelling, breaking the boundaries between digital and physical worlds. Experience the first comic book-style episode with realistic page-flipping using Turn.js technology.",
      image: "attachment:///moments/bangkok/2025-09-16/cover.png",
      imageAlt: "Urban Runner Episode 20: Comic Book Edition",
      caption: "Comic Book Edition - Breaking Digital Boundaries",
      fullLink: "/moments/bangkok/2025-09-16/",
      isComic: true,
      pageCount: 7, // Bangkok Episode 20 has 7 pages
      location: { lat: 13.7563, lng: 100.5018, name: "Bangkok, Thailand" },
      stayDuration: 1,
      formattedDuration: formatDuration(1)
    },
  {
    id: "istanbul-2025-09-24",
    title: "Istanbul Adventure",
    date: new Date('2025-09-24T00:00:00Z'),
    timelineHighlight: "Istanbul Exploration",
    tags: ["city", "culture", "history", "adventure", "turkey"],
    snippet: "Breaking up the Bangkok to Chicago journey with a week-long adventure in Istanbul. Exploring the crossroads of Europe and Asia, from the Blue Mosque to the Grand Bazaar, before heading to the wedding in Chicago.",
    fullLink: "#",
    location: { lat: 41.0082, lng: 28.9784, name: "Istanbul, Turkey" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
    {
      id: "istanbul-episode-2-2025-09-24",
      title: "Istanbul Episode 2: Crossroads of Cultures",
      date: new Date('2025-09-24T00:00:00Z'),
      timelineHighlight: "Istanbul Ep 2",
      tags: ["istanbul", "comic book", "turkey", "culture", "history", "bosphorus", "hagia sophia", "grand bazaar"],
      snippet: "Episode 2: Crossroads of Cultures - A comic book journey through Istanbul's most iconic landmarks. From the majestic Hagia Sophia to the bustling Grand Bazaar, experience the city where East meets West in this immersive visual storytelling adventure.",
      image: "attachment:///moments/istanbul/2025-09-24/cover.png",
      imageAlt: "Istanbul Episode 2: Crossroads of Cultures",
      caption: "Crossroads of Cultures - Where East Meets West",
      fullLink: "/moments/istanbul/2025-09-24/",
      isComic: true,
      pageCount: 16, // Istanbul Episode 2 has 16 pages (1-16)
      location: { lat: 41.0082, lng: 28.9784, name: "Istanbul, Turkey" },
      stayDuration: 1,
      formattedDuration: formatDuration(1)
    },
    {
      id: "istanbul-episode-3-2025-09-25",
      title: "Istanbul Episode 3: Layover in the Crossfire",
      date: new Date('2025-09-25T00:00:00Z'),
      timelineHighlight: "Istanbul Ep 3",
      tags: ["istanbul", "comic book", "turkey", "travel", "culture", "layover", "amman", "royal jordanian"],
      snippet: "Episode 3: Layover in the Crossfire - A comic book journey where saving $300 meant booking a risky route through Amman. From flight deals and car rentals to gym sessions, hookah cafés, Thai massages, and cultural reflections, this Istanbul day captured both hustle and recovery.",
      image: "attachment:///moments/istanbul/2025-09-25/cover.png",
      imageAlt: "Istanbul Episode 3: Layover in the Crossfire",
      caption: "Saving $300 meant an Amman layover in a war zone",
      fullLink: "/moments/istanbul/2025-09-25/",
      isComic: true,
      pageCount: 10, // Istanbul Episode 3 has 10 pages (1-10)
      location: { lat: 41.0082, lng: 28.9784, name: "Istanbul, Turkey" },
      stayDuration: 1,
      formattedDuration: formatDuration(1)
    },
    {
      id: "istanbul-episode-7-2025-09-30",
      title: "Istanbul Episode 7: Crossing the Bosphorus",
      date: new Date('2025-09-30T00:00:00Z'),
      timelineHighlight: "Istanbul Ep 7",
      tags: ["istanbul", "comic book", "turkey", "bosphorus", "hamam", "airport", "run", "galata tower"],
      snippet: "Episode 7: Crossing the Bosphorus - The ultimate Istanbul send-off. From laundry and morning rituals to a daring run across the bridge, a visit to the hamam, and a race through the mega-airport to catch the flight to Amman.",
      image: "attachment:///moments/istanbul/2025-09-30/cover.png",
      imageAlt: "Istanbul Episode 7: Crossing the Bosphorus",
      caption: "Crossing the Bosphorus - Istanbul Send-Off",
      fullLink: "/moments/istanbul/2025-09-30/",
      isComic: true,
      pageCount: 23, // Istanbul Episode 7 has 23 pages (1-23)
      location: { lat: 41.0082, lng: 28.9784, name: "Istanbul, Turkey" },
      stayDuration: 1,
      formattedDuration: formatDuration(1)
    },
  {
    id: "amman-2025-09-30",
    title: "Amman Layover - Smart Travel Strategy",
    date: new Date('2025-09-30T00:00:00Z'),
    timelineHighlight: "Amman Layover",
    tags: ["layover", "jordan", "work", "lounge", "travel strategy", "savings"],
    snippet: "Strategic 10.5-hour layover in Amman on the way to Chicago! Royal Jordanian's nice lounge provides the perfect spot to get work done, catch some sleep, shower, and recharge before the final leg. Saved $300 with this smart routing vs direct flight.",
    fullLink: "#",
    location: { lat: 31.9454, lng: 35.9284, name: "Amman, Jordan" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "chicago-2025-10-01",
    title: "Family Reunion & Wedding in Chicago",
    date: new Date('2025-10-01T00:00:00Z'),
    timelineHighlight: "Chicago Family",
    tags: ["city", "culture", "family", "wedding"],
    snippet: "Will attend my step-dad Mike's daughter's wedding (Oct 3-5) and have an emotional reunion with my dad after 16 years apart - we recently reconnected over the phone and he's excited to meet my brother and I in person. Flying in from Amman via Royal Jordanian after the strategic layover.",
    fullLink: "#",
    location: { lat: 41.8781, lng: -87.6298, name: "Chicago, Illinois" },
    stayDuration: 4,
    formattedDuration: formatDuration(4)
  },
  {
    id: "miami-2025-10-05",
    title: "Miami Beach & Culture",
    date: new Date('2025-10-05T00:00:00Z'),
    timelineHighlight: "Miami Vibes",
    tags: ["beach volleyball", "friends", "miami", "florida", "training", "crew"],
    snippet: "Post-wedding Miami reunion with the volleyball crew! Flying in from Chicago on Sunday to catch up with the team, training on South Beach, and soaking up the vibrant energy with the squad before flying to Lisbon for the work retreat.",
    fullLink: "#",
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  
  {
    id: "miami-episode-1-2025-10-06",
    title: "Miami Episode 1",
    date: new Date('2025-10-06T00:00:00Z'),
    timelineHighlight: "Miami Ep 1",
    tags: ["miami", "comic book", "urban runner", "florida", "beach", "culture"],
    snippet: "Episode 1: Miami — The first full day back in South Beach. From sunrise workouts at Muscle Beach and smoothie runs to raking rituals, volleyball wins, and spontaneous laughter with friends — a perfect Miami reboot.",
    image: "attachment:///moments/miami/2025-10-06/cover.png",
    imageAlt: "Miami Episode 1",
    caption: "Miami Episode 1 — South Beach Energy",
    fullLink: "/moments/miami/2025-10-06/",
    isComic: true,
    pageCount: 15, // Miami Episode 1 has 15 pages
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "miami-episode-2-2025-10-07",
    title: "Miami Episode 2 — Wynwood Ride, Tacos & Tests",
    date: new Date("2025-10-07T00:00:00Z"),
    timelineHighlight: "Miami Ep 2",
    tags: ["miami", "comic book", "wynwood", "bikeshare", "food", "volleyball", "health"],
    snippet:
      "Citi Bike over the Venetian, Wynwood walls, cheap-and-perfect tacos, award-winning gelato + espresso, a clean and confident clinic run (results in 5 days), a top-court beach volleyball win with Ash, and a laid-back dinner catch-up with Cat.",
    image: "attachment:///moments/miami/2025-10-07/cover.png",
    imageAlt: "Episode cover: biking to Wynwood with murals, tacos, gelato, and volleyball highlights.",
    caption: "Miami Episode 2 — Wynwood Ride, Tacos & Tests",
    fullLink: "/moments/miami/2025-10-07/",
    isComic: true,
    pageCount: 13,
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "miami-episode-3-2025-10-08",
    title: "Miami Episode 3 — Espresso & Endorphins",
    date: new Date("2025-10-08T00:00:00Z"),
    timelineHighlight: "Miami Ep 3",
    tags: [
      "miami",
      "comic book",
      "urban runner",
      "wellness",
      "language",
      "volleyball",
      "nightlife",
      "reflection"
    ],
    snippet:
      "From morning espresso to late-night reflections — a full Miami chapter. Began the day clean-cut and focused, hit Muscle Beach, navigated Wi-Fi chaos, sealed a perfume deal in Spanish at El Patio, and ended with rooftop luxury, deep talks, and a 5 a.m. Tootsie’s finale. A journey through energy, indulgence, and meaning.",
    image: "attachment:///moments/miami/2025-10-08/cover.png",
    imageAlt: "Episode cover: Miami morning reflection with red sunglasses.",
    caption: "Miami Episode 3 — Espresso & Endorphins",
    fullLink: "/moments/miami/2025-10-08/",
    isComic: true,
    pageCount: 11,
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "miami-episode-4-2025-10-09",
    title: "Miami Episode 4 — Side Out",
    date: new Date("2025-10-09T00:00:00Z"),
    timelineHighlight: "Miami Ep 4",
    tags: ["miami", "comic book", "volleyball", "south beach", "fitness", "recovery", "urban runner"],
    snippet:
      "A recovery day turned into one of the best volleyball sessions yet. Slept in after a 5 a.m. night, grabbed espresso, hit an open gym, fueled up with Miami Hack #3 — La Playa Market’s $20 feast, then dominated Side Out and 2v2 games through sunset. Ended the day showered, focused, and back at the desk getting work done.",
    image: "attachment:///moments/miami/2025-10-09/cover.png",
    imageAlt: "Episode cover: South Beach volleyball under a storm-to-sun sky.",
    caption: "Miami Episode 4 — Side Out",
    fullLink: "/moments/miami/2025-10-09/",
    isComic: true,
    pageCount: 4,
    location: { lat: 25.7617, lng: -80.1918, name: "Miami, Florida" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "miami-episode-7-2025-10-12",
    title: "Miami Episode 7: The Final Morning",
    date: new Date('2025-10-12T00:00:00Z'),
    timelineHighlight: "Miami Ep 7",
    tags: ["miami", "comic book", "urban runner", "travel day", "airport", "volleyball", "friendship"],
    snippet: "Episode 7: The Final Morning — From one last coffee with Cat to errands, bike rides, and Muscle Beach energy before flying out. A calm, reflective close to the Miami chapter, capped with a Turkish Lounge shower before Lisbon.",
    image: "attachment:///moments/miami/2025-10-12/cover.png",
    imageAlt: "Miami Episode 7 Cover",
    caption: "Miami Episode 7 — The Final Morning",
    fullLink: "/moments/miami/2025-10-12/",
    isComic: true,
    pageCount: 6,
    location: { lat: 25.7959, lng: -80.2870, name: "Miami International Airport" },
    stayDuration: 1,
    formattedDuration: formatDuration(1)
  },
  {
    id: "st-petersburg-2025-10-20",
    title: "St. Petersburg Mega Reunion",
    date: new Date('2025-10-20T00:00:00Z'),
    timelineHighlight: "St. Pete Mega Reunion",
    tags: ["family", "friends", "st petersburg", "florida", "relaxation", "reunion", "zacharias", "volleyball planning", "welli", "leo", "mo", "mom", "mike"],
    snippet: "Epic St. Pete reunion week! Catching up with Welli, Zacharias, Leo, Mo, Mom & Mike, and even more friends after the intense Lisbon work trip. Quality time with the whole crew, exploring familiar spots, and planning the Mexico tournament strategy with Zacharias before flying to Mexico on Sunday the 26th.",
    fullLink: "#",
    location: { lat: 27.7676, lng: -82.6403, name: "St. Petersburg, Florida" },
    stayDuration: 6,
    formattedDuration: formatDuration(6)
  },
  {
    id: "lisbon-2025-10-12",
    title: "Work Retreat in Lisbon",
    date: new Date('2025-10-12T00:00:00Z'),
    timelineHighlight: "Lisbon Work Trip",
    tags: ["work", "portugal", "team", "europe", "culture"],
    snippet: "Work get-together in beautiful Lisbon - flying direct from Miami to Portugal's capital for team collaboration and cultural immersion. Unfortunately will miss the Fuds volleyball tournament due to this work commitment, but still planning to make the Mexico tournament with Zacharias.",
    fullLink: "#",
    location: { lat: 38.7223, lng: -9.1393, name: "Lisbon, Portugal" },
    stayDuration: 7,
    formattedDuration: formatDuration(7)
  },
  {
    id: "playa-del-carmen-2025-10-26",
    title: "Beach Volleyball Tournament in Playa del Carmen",
    date: new Date('2025-10-26T00:00:00Z'),
    timelineHighlight: "Playa Volleyball",
    tags: ["beach volleyball", "beach", "friends", "tournament"],
    snippet: "After missing the Fuds volleyball tournament due to the Lisbon work trip, finally teaming up with Zacharias for our Mexico beach volleyball tournament! Flying from St. Pete on Sunday Oct 26th, giving us a full week in Mexico to prep, train, and enjoy Playa before the tournament (Fri Oct 31 - Sun Nov 2). This one was non-negotiable.",
    fullLink: "#",
    location: { lat: 20.6296, lng: -87.0739, name: "Playa del Carmen, Mexico" },
    stayDuration: 8,
    formattedDuration: formatDuration(8)
  },
  {
    id: "canggu-2025-11-03",
    title: "Yoga Retreat in Canggu",
    date: new Date('2025-11-03T00:00:00Z'),
    timelineHighlight: "Canggu Yoga",
    tags: ["yoga", "beach", "wellness", "friends"],
    snippet: "Will join Leigha, Hallie, and Leo for a rejuvenating yoga retreat amid Canggu's rice fields and beaches.",
    fullLink: "#",
    location: { lat: -8.6596, lng: 115.1326, name: "Canggu, Indonesia" },
    stayDuration: 21,
    formattedDuration: formatDuration(21)
  }
].sort((a, b) => a.date - b.date);