// characters.js - Full Character Bible for the comic book

window.characters = [
  {
    id: "paul",
    name: "Paul",
    role: "Main Character / Protagonist",
    description: "Urban Runner founder. Embodies the 4D life-documentation philosophy.",
    bio: "Confident minimalist traveler with a 'world in 60 lbs.' aesthetic. Explorer, digital nomad, intuitive decision-maker, trusted advisor to strangers, emotionally aware, disciplined yet spontaneous.",
    avatar: "/characters/Paul.png",
    pageImage: "/characters/Paul.png",
    imageAlt: "Paul - Urban Runner",
    tags: ["protagonist", "explorer", "digital-nomad"],
    relationship: "Protagonist and narrator"
  },
  {
    id: "greta",
    name: "Mom",
    role: "Mother / Matriarch",
    description: "Engineer, massage therapist, caregiver. A total badass who raised Paul and David.",
    bio: "Born in 1956. Has endured immense hardship yet remains a shining light. Stylish, strong, nurturing, endlessly supportive. Lives in Clearwater, FL.",
    avatar: "/characters/Mom.png",
    pageImage: "/characters/Mom.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mom.mp4",
    imageAlt: "Greta - Mom",
    tags: ["family", "mother", "anchor"],
    relationship: "The matriarchal anchor in Paul's life. Source of strength, love, and resilience."
  },
  {
    id: "brother",
    name: "Brother",
    role: "Family",
    description: "Paul’s older brother and one of the most important foundational relationships in his life.",
    bio: "Steady, grounded, and always supportive. Paul’s older brother has been a constant presence throughout every chapter of life. Protective but chill, logical yet funny, he brings a strong family anchor to Paul’s journey. Shares roots in Bulgaria and Chicago before life paths diverged. Represents the importance of family threads that stay intact across time and distance.",
    avatar: "/characters/Brother.png",
    pageImage: "/characters/Brother.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Brother.mp4",
    imageAlt: "Paul’s Brother",
    tags: ["family", "brother", "roots"],
    relationship: "Older brother — lifelong anchor, shared childhood, shared history."
  },
  {
    id: "wellington",
    name: "Welli",
    role: "Friend / Business Leader",
    description: "Dominican entrepreneur, bar/restaurant operator, future St. Pete mayor energy.",
    bio: "Multi-business owner in St. Pete. Rose from Ubering to operating multiple venues. Dog dad to Duke. Direct, sharp eye for detail, inspiring growth.",
    avatar: "/characters/Welli.png",
    pageImage: "/characters/Welli.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Welli.mp4",
    imageAlt: "Welli",
    tags: ["friend", "entrepreneur", "volleyball"],
    relationship: "Lifelong friend; part of the brotherhood with Zacharias."
  },
  {
    id: "leo",
    name: "Leo",
    nickname: "Responsiblor",
    role: "Lifelong Friend / Mentor Figure",
    description: "Older, mature, driven, tech-loving friend. Met through volleyball in Chicago.",
    bio: "Filipino. Organizer of the Mafia volleyball group. Splits time between St. Pete and the Philippines. Giving, caring, methodical. Deeply influential in Paul's life.",
    avatar: "/characters/Leo.png",
    pageImage: "/characters/Leo.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leo.mp4",
    imageAlt: "Leo - Responsiblor",
    tags: ["friend", "volleyball", "mentor", "philippines"],
    relationship: "Lifelong friend who helped shape Paul's adult years."
  },
  {
    id: "mo",
    name: "Mo",
    role: "Close Friend / Brother",
    description: "One of Paul's closest long-term friends. Met in St. Pete through volleyball.",
    bio: "Born in Pakistan. Ex-professional rugby player. Calm, grounded aesthetic. Kind, forgiving, patient. Devoted father of two. Represents loyalty, brotherhood, and depth.",
    avatar: "/characters/Mo.png",
    pageImage: "/characters/Mo.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mo.mp4",
    imageAlt: "Mo - Close Friend",
    tags: ["friend", "volleyball", "father", "loyalty"],
    relationship: "Recurring anchor across cities and life chapters."
  },
  {
    id: "zacharias",
    name: "Zacharias",
    role: "Close Friend / Brother-In-Arms",
    description: "Programmer, volleyball player, charismatic thinker, lifelong friend of Welli.",
    bio: "Funny, charming, logical, and ambitious. Zacharias is a lifelong friend of Wellington and an essential part of Paul's Florida chapter. Originally from New York, he chose to relocate to St. Pete after falling in love with the community. A talented programmer and explosive volleyball player, he invited Paul to play the Mexico Tournament two years in a row. Known for his sharp humor, strategic mind, and smooth charisma. Currently dating Victoria. Comes from a political lineage and carries that part-politician charm.",
    avatar: "/characters/Zacharias.png",
    pageImage: "/characters/Zacharias.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Zacharias.mp4",
    imageAlt: "Zacharias - Close Friend",
    origin: "New York, USA",
    currentHome: "St. Petersburg, Florida",
    tags: ["friend", "volleyball", "programmer", "thinker", "charming"],
    relationship: "Close friend of Paul. Volleyball partner for multiple Mexico tournaments; lifelong brotherhood with Wellington."
  },
  {
    id: "sandro",
    name: "Sandro",
    role: "Friend / Volleyball Brother",
    description: "High-energy, joyful presence on and off the sand.",
    bio: "Volleyball brother from the St. Pete crew. Known for big smiles, big swings, and big heart energy when the squad links up.",
    avatar: "/characters/Sandro.png",
    pageImage: "/characters/Sandro.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sandro.mp4",
    imageAlt: "Sandro - Volleyball Brother",
    tags: ["friend", "volleyball", "st-pete"],
    relationship: "Part of the extended volleyball family that shows up across chapters."
  },
  {
    id: "wouter",
    name: "Wouter",
    role: "Friend / Brother / Travel Companion",
    description: "One of those rare friends who feels more like a brother forged through shared miles than time alone.",
    bio: "Wouter is one of those rare friends who feels more like a brother forged through shared miles than time alone. Athletic, sharp-featured, with piercing blue eyes and a calm confidence, he carries himself with an easy balance of discipline and fun. He's adventurous without being reckless, social without needing the spotlight, and grounded even when life gets chaotic. Wouter and Paul have crossed continents together — from Medellín to Miami, Germany to Cuba, Dubai to Abu Dhabi — collecting stories through late nights, intense conversations, workouts, beaches, and moments that only happen when you travel with someone you fully trust. He has a strong physical presence but an even stronger sense of loyalty. He's the type who shows up, adapts fast, and turns unfamiliar places into home bases. Currently living in Valencia, Spain, Wouter has his eyes set on South Beach, Miami — drawn to the energy, movement, and sun. He represents momentum, brotherhood, and the kind of friendship that evolves alongside personal growth. In the Urban Runner universe, Wouter is not a side character — he's a parallel path, a fellow traveler, and part of the core tribe that makes the journey real.",
    avatar: "/characters/Wouter.png",
    pageImage: "/characters/Wouter.png",
    imageAlt: "Wouter - Friend",
    origin: "Netherlands",
    currentHome: "Valencia, Spain",
    tags: ["friend", "brother", "travel", "volleyball", "yoga", "valencia", "miami", "brotherhood", "athletic"],
    relationship: "A brother forged through shared miles. Parallel path, fellow traveler, and part of the core tribe that makes the journey real."
  },
  {
    id: "boy",
    name: "Boy",
    role: "Social Catalyst / Wild Card / Leo's Brother",
    description: "Raw social momentum — the kind of person who turns any quiet night into a story without ever meaning to.",
    bio: "Boy is raw social momentum — the kind of person who turns any quiet night into a story without ever meaning to. Leo's brother and a social catalyst who creates momentum just by being present. Outgoing, high-energy, charismatic, and shamelessly social. A natural womanizer in the most effortless way — not calculated, just instinctual. Extremely comfortable talking to anyone, anywhere. Thrives in group settings, nightlife, and spontaneous plans. Bold without being insecure; playful rather than aggressive. Acts first, thinks later — but rarely in a way that causes damage. Loyal to his brother Leo, often pulling him into more chaotic social situations. He's not introspective or philosophical — he's kinetic. Movement, people, noise, energy. When Boy is in a scene, the probability of meeting new people spikes, nights extend longer than planned, and the story shifts from observation to participation. He brings Davao street confidence into every city he appears in. Friendly and open with Paul, instantly familiar. Less about deep talks, more about shared experiences. Pulls Paul out of analysis mode and into action. Represents a version of freedom rooted in social instinct rather than self-optimization. Primary base: Valencia (Davao). Strongest presence in Davao, group travel scenes, and nightlife arcs.",
    avatar: "/characters/Boy.png",
    pageImage: "/characters/Boy.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Boy.mp4",
    imageAlt: "Boy - Social Catalyst",
    origin: "Davao, Philippines",
    currentHome: "Valencia, Davao",
    tags: ["friend", "philippines", "family", "brother", "social", "nightlife", "charismatic", "wild-card"],
    relationship: "Leo's brother and social catalyst. Friendly, open, instantly familiar. Pulls Paul out of analysis mode and into action. Represents freedom rooted in social instinct."
  },
  {
    id: "sean",
    name: "Sean",
    role: "Friend / Siargao Local",
    description: "Friend of Boy and Leo who lives on Siargao. Deeply familiar with the island and part of the Philippines crew.",
    bio: "Friend of Boy and Leo who lives on Siargao most of the time, making him deeply familiar with the island. Met Paul in Bangkok and Manila before their Siargao reunion. Part of the Philippines crew and the extended friend group. Sean's local knowledge and island familiarity made him an ideal guide for exploring Siargao. He introduced Paul to Maria, connecting the musical muse to the Siargao experience. Represents the local connections and deep island knowledge that make travel experiences richer. Part of the group adventures in Bangkok with Boy and the crew from Chicago and Atlanta. Primary arc: Siargao.",
    avatar: "/characters/Sean.png",
    pageImage: "/characters/Sean.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sean.mp4",
    imageAlt: "Sean - Siargao Local",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "philippines", "local", "crew"],
    relationship: "Friend of Boy and Leo. Lives on Siargao and deeply familiar with the island. Introduced Paul to Maria and provided local insights during the Siargao stay."
  },
  {
    id: "hallie",
    name: "Hallie",
    nickname: "Mighty Mouse",
    role: "Friend",
    description: "Optimistic, social, warm presence. Fairy energy. Part of the Bali friend trio.",
    bio: "Yoga teacher turned studio manager overseeing 100+ people. Sweet, kind, grounded, recently engaged. Dreams of owning a studio and being a mom.",
    avatar: "/characters/Hallie.png",
    pageImage: "/characters/Hallie.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Hallie.mp4",
    imageAlt: "Hallie - Mighty Mouse",
    tags: ["friend", "bali", "yoga"],
    relationship: "Supportive and joyful friend; Bali reunion during Leigha's retreat."
  },
  {
    id: "leigha",
    name: "Leigha",
    role: "Friend",
    description: "Warm, magnetic, and grounded — equal parts nurturer and free spirit.",
    bio: "Yoga teacher, nurse, photographer, and community builder. Organizer and host of the Bali Yoga Retreat. Deeply rooted in beach-town energy, with a bohemian aesthetic and a natural ability to bring people together.",
    avatar: "/characters/Leigha.png",
    pageImage: "/characters/Leigha.png",
    imageAlt: "Leigha - Friend",
    tags: ["friend", "bali", "yoga", "boho", "retreats", "beach-town"],
    relationship: "Retreat host and close friend; part of the Bali friend trio with Hallie.",
    traits: [
      "bubbly",
      "empathetic",
      "confident",
      "expressive",
      "community-oriented"
    ],
    archetype: "The Connector"
  },
  {
    id: "jamie",
    name: "Jamie",
    role: "Remote Collaborator",
    description: "Adventurous, playful remote collaborator.",
    bio: "Remote contributor to Urban Runner. Sends assets from abroad and appears in multiple episodes.",
    // avatar/pageImage will be added once artwork is ready
    tags: ["collaborator", "remote"],
    relationship: "Remote collaborator expanding the UR world."
  },
  {
    id: "tony",
    name: "Tony (Chelsea Fan)",
    role: "Recurring NPC",
    description: "Chill, observant, recurring ambient character at Amsterdam Café.",
    bio: "Chelsea fan. Recognizable recurring NPC in Bangkok. Cool, low-key presence.",
    // avatar/pageImage will be added once artwork is ready
    tags: ["npc", "recurring"],
    relationship: "Recurring ambient presence in Bangkok episodes."
  },
  {
    id: "aime",
    name: "Aime",
    role: "Romantic Interest",
    description: "Sweet, elegant, quirky (prefers sour mangos).",
    bio: "Romantic, thoughtful, graceful energy. Appears in the Chinatown stroll episode.",
    // avatar/pageImage will be added once artwork is ready
    tags: ["romantic-interest"],
    relationship: "Romantic interest; memorable Chinatown stroll."
  },
  {
    id: "jeandel",
    name: "Jeandel",
    role: "Short-Term Companion / Romantic Interest",
    description: "The city girl who took the leap to island life, bringing a mix of youthful energy, drama, and genuine connection into a short but memorable chapter of the Urban Runner story.",
    bio: "Jeandel is the city girl who took the leap to island life, bringing a mix of youthful energy, drama, and genuine connection into a short but memorable chapter of the Urban Runner story. Warm, easygoing, and playful. Emotionally present, but young and still navigating her own boundaries. Open to new experiences, but can bring a bit of drama due to her age and life stage. Met in Manila through Bumble, where she quickly became a consistent part of daily life: coffee runs, downtime, and a slower, more lived-in rhythm. She agreed to come to Siargao, which turned the Manila mission into a successful crossover from city to island life. In Siargao, she brought a mix of joy and challenge. Paul stepped into a provider role, which felt rewarding but also a bit draining at times. Her youthful energy (around 23) added emotional intensity to the experience. Serves as the emotional and narrative payoff of the Manila mission, proving that finding someone genuine wasn't just a fantasy. A character who transitions from one environment to another, adding depth and relational complexity. A short-term companion who brought both enjoyable moments and challenges, ultimately helping clarify what Paul does and doesn't want in a longer-term partner. Primary arc: Manila transitioning into Siargao.",
    avatar: "/characters/Jeandel.png",
    pageImage: "/characters/Jeandel.png",
    imageAlt: "Jeandel - Short-Term Companion",
    origin: "Manila, Philippines",
    tags: ["romantic-interest", "manila", "siargao", "short-term", "companion", "philippines"],
    relationship: "Short-term companion from Manila who joined Paul in Siargao. Brought youthful energy, genuine connection, and helped clarify relationship boundaries. Mission companion for the Manila → Siargao arc."
  },
  {
    id: "maria",
    name: "Maria",
    role: "Local Friend / Musical Muse",
    description: "Incredibly talented singer with a soulful presence. A musical muse who adds artistic and cultural richness to the Siargao arc.",
    bio: "Maria is an incredibly talented singer with a soulful presence, perhaps the best singer Paul has ever met. Warm, welcoming, and comfortable in intimate settings. A mix of creative energy and laid-back island lifestyle. Not just a local guide; she's a musical soul who brings a special artistic dimension to the Siargao chapter. Loves to perform in cozy, intimate settings. Spent a lot of time with Paul both at his place and her apartment, sharing music, smoking marijuana together, and enjoying the creative flow. Serves as a musical muse who adds a layer of artistic and cultural richness to the Siargao arc. A character who deepens the sense of community and creativity on the island, making it more than just a scenic getaway. Shows that island life can be both laid-back and creatively vibrant. Met through Sean. The connection with Maria is rooted in shared artistic moments and mutual enjoyment of music. She's a friend and creative partner, someone who enriches time on the island through her talent and easygoing friendship. The bond is more about shared creativity and relaxation than romance. Primary arc: Siargao.",
    avatar: "/characters/Maria.png",
    pageImage: "/characters/Maria.png",
    imageAlt: "Maria - Musical Muse",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "music", "singer", "creative", "local", "philippines"],
    relationship: "Local friend and musical muse from Siargao. Met through Sean. Friend and creative partner who enriches the island experience through shared music and artistic moments. The bond is about shared creativity and relaxation."
  },
  {
    id: "august",
    name: "August",
    nickname: "The Fairy",
    role: "Supporting Character / Whimsical Companion",
    description: "August (The Fairy) is the island's touch of whimsy — a free-spirited friend who turns ordinary days into something a bit more magical.",
    bio: "August (The Fairy) is the island's touch of whimsy — a free-spirited friend who turns ordinary days into something a bit more magical. August earned the nickname 'The Fairy' because of her almost otherworldly, carefree vibe. Ethereal, free-spirited energy. Light-hearted and whimsical, with a natural charm that feels almost magical. Someone who brings a touch of playfulness and otherworldliness to everyday moments. Effortlessly enchanting and has a way of making ordinary experiences feel a bit magical. Laid-back and brings a sense of fun and lightness wherever she goes. Serves as a free-spirited companion who adds a whimsical layer to the Siargao arc. Someone who makes even simple moments feel a bit more magical and carefree. A character who encourages embracing a more playful, lighthearted side of island life. August is a friend who adds a layer of whimsy and relaxation to the Siargao experience. Her presence is more about shared fun and light-hearted moments than deep conversations. She's someone who helps unwind and enjoy the more carefree side of island life. Eligible for: Light-hearted scenes, beach gatherings, and any moments that call for a bit of fairy-like magic and playfulness. Primary arc: Siargao.",
    avatar: "/characters/Fairy.png",
    pageImage: "/characters/Fairy.png",
    imageAlt: "August - The Fairy",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "free-spirit", "whimsical", "companion", "philippines", "supporting"],
    relationship: "Free-spirited companion from Siargao. Adds whimsy and relaxation to the island experience. Helps embrace the playful, lighthearted side of island life through shared fun and carefree moments."
  },
  {
    id: "kj",
    name: "KJ",
    role: "Friend / Dance Partner",
    description: "Kind, confident, spiritually attuned. Magnetic dancer with bold energy.",
    bio: "Born in Houston, raised in Austin. Works in Ayurvedic retreats. Spiritual, artistic, expressive. Known for the 'twerk moment' in Ubud.",
    avatar: "/characters/KJ.png",
    pageImage: "/characters/KJ.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/KJ.mp4",
    imageAlt: "KJ - Friend",
    tags: ["friend", "bali", "dance", "spiritual"],
    relationship: "Electric connection in Ubud. Powerful dance-floor chemistry."
  },
  {
    id: "thai-dragon",
    name: "Thai Dragon",
    role: "Friend / Thailand Arc Character",
    description: "Mysterious, calm, elegant presence from Thailand.",
    bio: "Follower of the Urban Runner comic. Sleek look, confident energy, iconic black dress and gold pendant. Requested her own comic entry.",
    avatar: "/characters/ThaiDragon.png",
    pageImage: "/characters/ThaiDragon.png",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/ThaiDragon.mp4",
    imageAlt: "Thai Dragon",
    tags: ["friend", "thailand", "dragon"],
    relationship: "Symbolic character of the Thailand arc."
  },
  {
    id: "khanh",
    name: "Khanh",
    role: "Friend / Travel Companion / Mirror",
    description: "Chicago volleyball crew member who spent 5+ years in Hawaii, now traveling through Southeast Asia with Paul.",
    bio: "Long-time friend from Paul's Chicago volleyball days who helped him move to Florida before diverging paths. After 5-6 years establishing his own rhythm in Hawaii, Khanh reconnected with Paul for an Asia adventure before a job opportunity in California. Health-conscious, boundary-aware, and endlessly social, Khanh transforms through the journey: from dependent (visa issues, sickness) to independent (agency, self-care) to autonomous (making his own path). His role in Urban Runner is as The Mirror — teaching Paul about accepting difference, respecting autonomy within friendship, and grounding through genuine connection. Athletic, thoughtful, and deeply loyal.",
    avatar: "/characters/Khanh.png",
    pageImage: "/characters/Khanh.png",
    imageAlt: "Khanh - Travel Companion",
    origin: "Chicago, USA",
    baseLocations: ["Hawaii (5-6 years)", "Vietnam (Da Nang, Ho Chi Minh)", "Thailand (Bangkok)"],
    tags: ["friend", "volleyball", "travel", "chicago", "hawaii", "vietnam", "thailand", "brother"],
    relationship: "Chicago crew member, Hawaii years, Asia travel buddy. Teaches Paul about acceptance, boundaries, and autonomous friendship. The Mirror of the Vietnam arc.",
    keyScenes: ["The Arrival (Saigon reunion)", "The Pamper Day (self-care)", "The Raid (gaming life)", "The Boundary (different rhythms accepted)"],
    episodes: ["Heaven on Earth (Feb 7)", "The Arrival (unpublished)", "The Pamper Day (unpublished)", "The Raid (unpublished)"],
    characterArc: "Dependent (visa issues, sickness) → Independent (agency, self-care) → Autonomous (own path toward California)"
  }
];

window.characterComicBook = {
  id: "characters-comic-book",
  title: "Character Bible",
  description: "Meet all the characters in Paul's life story",
  cover: "/characters/cover.png",
  fullLink: "/characters/",
  pages: window.characters
    .filter(c => !!c.pageImage) // Only include characters with a defined image
    .map((c, i) => ({
    number: i + 1,
    character: c.id,
    image: c.pageImage,
    video: c.pageVideo || null,
    alt: c.name,
    bio: c.bio,
    description: c.description,
    name: c.name,
    role: c.role
  })),
  isComic: true
};
